Haz3l user defined operators
hazelgrove/hazel pull request #1012
Opened 2023-05-14 17:52 UTC by shawn-stovall

Adding the ability for users to define their own operators.

This pull request makes changes to the external language's pattern and expression forms so that custom infix operators can be defined and applied. This then elaborates to an applied `DHExp.t` of the form `Ap(operator_variable, Tuple([arg1, a rg2]))`. The evaluator then continues unmodified to process the function application.

Features:

- `_op_` can be used in a normal let to define a new operator
- `arg1 op arg2` can then be used without the underscores to apply the operator's function

Potential Future Features:

- `_op_` can be used in expressions to allow for typical function application (of the form `_op_(arg1, arg2)`).
- `_op` and `op_` used to define postfix and prefix operators, respectively.

2023-05-26 15:38 UTC, shawn-stovall commented
User-defined operators are working with the following features:

* `_op_` defines a user-defined operator, with op representing one or more of the following symbols: `~?!$%&*+\\-./:<=>@^`
Precedence and associativity are decided by the first character of the operator. I used the list of valid operator symbols from Ocaml to determine which symbols to include in this list, as well as `~?!` which are usually reserved for different fixities in Ocaml. The precedence of the first character is determined by the matching precedence of the built-in operator of the same symbol. For the symbols not in Hazel, I used Ocaml precedence as a reference. The exceptions to this are `~!?` to which I gave the precedence of equality.
* Calling the operator surrounded by parentheses in the form `_op_(arg1, arg2)` calls the operator as a normal function.
* There are user-facing errors for defining an operator that is the same as a built-in operator, defining an operator that is bound to a non-binary function definition, and and error for trying to call an undefined operator (which uses the standard "variable not defined" error).

2023-06-06 19:47 UTC, cyrus- commented
Error message here should say something about user-defined operator being unbound, not that it is not a binary function. 

<img width="1202" alt="image" src="https://github.com/hazelgrove/hazel/assets/280638/8fe8ae65-8a71-4716-8b85-a818c7a7426a">

2023-06-06 19:48 UTC, cyrus- commented
Error box here is broken (when function extends over more than one line)

<img width="521" alt="image" src="https://github.com/hazelgrove/hazel/assets/280638/b8820563-ef40-4e8a-ba2f-6caf13457e01">

2023-06-06 19:50 UTC, cyrus- commented
Operator definition error should appear only if the type of the bound expression is not *consistent* with a binary function, even if it isn't exactly of the form (t1, t2) -> t3. So the hole type or hole -> t3 things like that are fine. Casts will handle downstream problems.

<img width="372" alt="image" src="https://github.com/hazelgrove/hazel/assets/280638/7935e0cf-ed5c-45db-a5c2-e0a667eea407">

2023-06-06 19:52 UTC, cyrus- commented
Let's also update the scratch slide 1 (language reference) to list out all of the operators in order of precedence and include a comment describing how user-defined operators work (precedence and associativity).

2023-06-06 19:56 UTC, cyrus- commented
Nice work, seems like just a few polish things are remaining! Marking as draft again based on incomplete functional review comments above, will continue to take a look once those things are addressed.

2023-07-30 20:59 UTC, cyrus- requested changes
I can't type `f` into the second hole here:
<img width="622" alt="image" src="https://github.com/hazelgrove/hazel/assets/280638/e1186201-8ab3-4e98-bf1f-19bf21cae84f">

2023-08-14 19:21 UTC, cyrus- commented
@shawn-stovall quite a few conflicts with `dev` after recent ADTs merge, can you take a look at those?

2023-08-19 19:30 UTC, disconcision commented
I've been thinking lately about grammatical concerns for characters that can live in tokens of more than one grammatical class. (for our purposes here grammatical classes comprise the following:

- operand
- infix operator
- prefix operator
- postfix operator
- form delimiter (eg 'let', '=', and 'in'; technically this should maybe divide into multiple classes)

Even without user-defined operators, this already creates some ambiguities in our grammar:

1. '.' occurs in both operands (floating points) and infix operators (==. !=. <. >. <=. >=.). thus the following program has an ambiguous parse: 1==.1 could be (1)==.(1) or (1)==(.1). Currently the accepted parse is the first, but this is somewhat incidental, due to the fact that we attempt to append an inserted character to the left first before the right. If we explicitly choose to allow such ambiguities, we should probably clarify some general principles for disambiguation; either formalize the left to right model, choose a prioritization based on syntactic class, special-case per-ambiguity, etc.
2. '-' occurs as both infix and prefix operator; this manifests in remolding bugs such as #1076, which are sensitive to which order the two alternatives appear in in Forms.re.
3. '+' occurs as both infix and prefix operator too, though only for types, and in a way that isn't semantically ambiguous
4. '!' occurs as prefix and (as part of an) infix operator, though it currently only exists in infix ops as a leading character, so this ambiguity does not currently manifest
5.  '->' occurs as both infix and form delimiter; this is already a collision between function types and function literals; see bug #970)
6. '=' occurs as form delimiter (let expressions) and is potentially infix; if realized, this would cause a similar ambiguity to '->'
7. '=>' likewise occurs as form delimiter (case rules) and is potentially infix

Other than the last one, none of these are _further_ problematized by the allowed character list of user-defined operators, so this is mostly food for thought, except that the last three cases should probably be forbidden as user-defined operators

2023-12-18 00:16 UTC, disconcision commented
I did a functional review. There are still a few outstanding bugs, and a couple other things we should probably decide about. Going to reproduce the things I tried below for reference:
<img width="692" alt="Screen Shot 2023-12-17 at 7 00 57 PM" src="https://github.com/hazelgrove/hazel/assets/22436459/6c8939bb-be4b-44fe-8349-beef23963a69">

`
#1. OK: dont shadow builtins#
let _*_ = in
let _!_ = in

#2. OK? Do we want to still bind failed operator defs? We do at the moment#
let _*--_ = 1 in
let _*---_ = fun x, y, z -> x + y in

#3. Bug: Should probably be a static error#
let _*-*-_ = fun x:Int -> 1 in

#4. OK: Constant operator. Pointless but fine#
let _*+*+_= fun x: -> 1 in

#5. OK?: Returns pair of inputs. Odd but fine I guess?#
let _*!*+_= fun x: -> x in

#6. OK? Runtime cast fail; not wrong but not ideal#
let _*---*_= fun x-> let a,b,c = x in a+b in
#Maybe we should require that unannotated ops analyze against (?,?)->?#
#This would make 3 and 6 static errors.#

#7. OK: Happy unannotated cases#
let _*----_ = fun x, y -> x + y in
let _+*_= fun x-> let a, b = x in a*b in

#8. OK? Notice error is localized to pattern here#
# It would be on definition if this wasnt an operator #
# This seems reasonable, but the message shown DOES involve the definitions#
# type. if were going to attribute the err to the annotation, i feel the#
# message should be more like "must be consistent with (?,?)->?" or something#
let _+***_: (Int, Int) = fun a,b-> a*b in

#9. OK: Annotated happy path #
let _*---*_: (Int, Int) -> Bool = fun a, b -> a < b in 

#10. Bug: All unnannoted operators trigger cast exceptions when used in tests:#
test 1+*1 == 1 end;

#11. OK: Use operator as fn#
_*---*_(4,4);

#12. OK? Maybe out-of-scope but would be nice to be able to do above w/builtins#
_*_(4,4)
`

Bugs:
- Unannotated ops defs which don't take a tuple should be static errors (see 3). I propose new logic in (6) which would catch this and maybe subsume the current logic. In summary, maybe the logic should be something like: (A) For an unannotated operator, the definition must analyze against (?,?)->?. (B) For an annotated operator, we still want the definition to analyze against (?,?)->?, so we would need to either insist the the def analyze against that AND against the annotation (potentially confusing), or insist that the annotation must be equally or more specific than (?,?)->? (sort of picky)
- There seems to be a casting bug for unannotated operators (see 10).

Things to decide:
- Should failed operator definitions (invalid type) still get bound in context (see 1)
- The 'identity operator', which just returns the pair of its inputs, feels slightly odd to me, but I don't think it's worth special-casing to avoid. (see 5)
- The error we put on bad operator annotations could maybe be more targetted (see 8)
- Would be nice to be able to use extant builtin (functional) ops as fns as well, but maybe not necessary for this PR (see 12)

2026-04-21 12:55 UTC, cyrus- commented
archiving since this is no longer active

2026-04-21 12:55 UTC, closed without merging