Basic functionality working, prints correctly to console
hazelgrove/hazel pull request #1033
Opened 2023-05-27 18:14 UTC by lmulcahy21

The basic functionality of the warnings works correctly, printing "unused [var name]" or "used [var name]" to the console. 

Would love review on these changes, as this does alter some of the core functionality of the backend, as well as the function definition for `upat_to_info_map`. 

After review and revision, next step is to merge in the `adt-defs-refutable` branch and implement a warning for this, so that the variable is highlighted in place.

2023-05-31 16:11 UTC, disconcision requested changes
Looks good! Some cleanup and case/lambda still need wiring up. Then prob good to proceed with bringing in warnings code

2023-05-31 16:11 UTC, disconcision commented on src/haz3lcore/statics/Ctx.re
> +let is_unused_in_free = (free: co, name: string): option(bool) => {
a co_ctx is a VarMap so you can use VarMap.lookup. This fn should probably just be a one-liner,something like
let co_ctx_contains = (free, name): bool =>  VarMap.lookup(free,name) !=None, and then at the call site you not it to get the opposite

2023-05-31 16:11 UTC, disconcision commented on src/haz3lcore/statics/Statics.re
> +      ~free: Ctx.co=[],
at least as an implementation strategy, i suggest removing the default value of this parameter (yes, i remember that i told you to add it :) to make sure you examine all the use sites (e.g. the logic you've added for the let should be added for case & lambda as well). if there aren't that many call sites i would suggest just leaving it non-optional and specifying an empty free for callsites that would use the default value... your call, this is a tradeoff

2023-05-31 16:11 UTC, disconcision commented on src/haz3lcore/statics/Statics.re
> +    let self_pat_val: Info.self_pat =
it looks like this doesn't actually do anything at the moment? the second switch just ignores the value of self_pat_val?

regardless, when this is hooked up, split this logic off into a helper in Statics called pat_var_self. (in general i try to keep the main mutually recursive statics functions terse; they should only handle the piping of data between the different parts of the syntax, and all logic should be split into helpers)

2023-06-01 19:27 UTC, lmulcahy21 commented
Just made a commit implementing most of these suggestions, but needs more time/work for debugging case statements. They currently aren't evaluating and the use of a variable in the case statement isn't counting as a "use" for the state of the variable, and im pretty sure it has something to do with an empty free/co-ctx instead of a properly created/propagated one

2024-04-11 18:40 UTC, lmulcahy21 commented
UVWs are working, with a basic warning interface outlined through the Info module. Would love to get feedback on it, as many things could use improvement, such as the names of warnings, info that each displays, how they are found, etc.

2024-04-11 19:56 UTC, cyrus- commented
Nice work! 

It isn't handling recursive functions correctly, so maybe look into that: 
![image](https://github.com/hazelgrove/hazel/assets/280638/f8ee6ab2-b9a6-4f65-8cc5-2b6a609c083a)

Another thing we should think about is how to handle variables where there is an empty expression hole in the scope. We think of holes as being potentially filled by anything, including that unused variable, so in such a case I would call the variable "possibly unused" rather than "definitely unused". I think we should hold off on displaying the warning marker in that situation.

2024-04-13 19:55 UTC, lmulcahy21 commented
Also no working correctly for case statements, will look into this

<img width="446" alt="image" src="https://github.com/hazelgrove/hazel/assets/71798334/ee3a478b-c80e-4404-9b26-440fcf2e7f95">

2024-05-28 02:37 UTC, cyrus- commented
@lmulcahy21 
* need to resolve some merge conflicts
* the message in the cursor inspector needs to be human-readable
* we need to have it so if there is a hole in the scope of a variable, we don't show unused variable warnings, otherwise we end up with stuff like this in exercises mode where odd is showing as unused because it isn't explicitly used in the "in" portion (but it will be referred to by the tests etc. downstream in exercises mode):
<img width="1449" alt="image" src="https://github.com/hazelgrove/hazel/assets/280638/5106ec46-8709-4691-a0fe-bce8a7f9c931">

2024-06-14 02:07 UTC, lmulcahy21 commented
Had a boxing match with git and lost (had to force push) but warnings now (inelegantly) don't display if there is a hole in the co-context; done with a `__hole__` variable in the co-context, as i didn't want to change the current co-ctx's interface

2024-06-18 18:03 UTC, disconcision requested changes, later dismissed
looking pretty good but wondering about a couple details of the approach

2024-06-18 18:03 UTC, disconcision commented on src/haz3lcore/statics/Statics.re
> +        switch (VarMap.lookup(co_ctx, name)) {
factor out these three conditions into a separate named predicate fn

2024-06-18 18:03 UTC, disconcision commented on src/haz3lcore/statics/Statics.re
> +    );
we should ideally avoid having separate passes over the entire info_map where possible. probably want to either merge this with error_ids as a single pass which returns a pair or record of two lists, or maybe make this pass return a single list of some perhaps new data type which covers multiple classes of 'distinguished' ids (right now, Errors and Warnings)

2024-06-18 18:03 UTC, disconcision commented on src/haz3lcore/statics/Statics.re
> +        (p_ctx, e_co_ctx) => CoCtx.mk(ctx, p_ctx, e_co_ctx),
cant this just be eta-reduced to previous?

2024-06-18 18:03 UTC, disconcision commented on src/haz3lweb/www/style.css
> +    /* HACK(liam copying andrew) */
lmao, but fair

2024-06-18 18:03 UTC, disconcision commented on src/haz3lcore/statics/Info.re
> +[@deriving (show({with_path: false}), sexp, yojson)]
was hoping we could have warnings as part of the status type, as another top-level entry alongside InHole and NotInHole. (but not sure if this is right approach), is there a reason this doesn't work out?

2024-06-18 18:03 UTC, disconcision commented on src/haz3lcore/statics/CoCtx.re
> +let contains_hole = (co_ctx: t): bool =>
fine but document

2025-06-30 19:04 UTC, disconcision commented
![Screenshot 2025-06-30 150422](https://github.com/user-attachments/assets/432cc535-84cf-4bbf-b7ea-fff27754de1b)

seems to be claiming everything as unused

2025-06-30 19:11 UTC, lmulcahy21 commented
@disconcision working on a toggle for warnings right now to avoid this problem, as those are correctly marked as unused in the documentation page, and having the screen be covered in yellow like that is not ideal.

2025-07-12 18:28 UTC, lmulcahy21 commented
@disconcision ready for review, have added switch for warning visibility toggling, made the color less harsh, and fixed how co-contexts are handled for case statements such that the patterns correctly see variable uses from the corresponding expression

2025-07-16 01:59 UTC, disconcision requested changes
1. let's go with some slightly less aggressive colors. something like:

<img width="1151" height="1366" alt="Screenshot 2025-07-15 211959" src="https://github.com/user-attachments/assets/77e98461-fe78-457c-a2af-16ab64461247" />

either use those colors, or better yet, you could look at the oklch in variables.css for the red colors used for error hole fill and stroke and just copy those leaving the L and C the same but making the hue orange.

2. for the warning message itself, how would you feel about instead of `Warning: Unused variable <x>`, `Warning: Variable <x> is never used`? minor, just feels like more of a sentence to me.

3. pending the color change, i think these should be on by default. perhaps the documentation slides that don't reference most things they define could be updated to be more naturalistic 

Looks very solid! The only things which are blockers for me is the color change and checking if that threading of ~warning can be removed from statics as per the code comments. the others are nice-to-haves

2025-07-16 01:59 UTC, disconcision commented on src/language/statics/Info.re
> +    }
`let is_warning = ci =>warning_of(ci) != None`

2025-07-16 01:59 UTC, disconcision commented on src/web/www/style/variables.css
> +  --select-z: 5;
why this change? ie does anything go wrong if errors and warnings have the same z-index?

2025-07-16 01:59 UTC, disconcision commented on src/web/www/style/dynamics.css
> +
is this actually used? i thought DHCode stuff was dead code now. maybe check this

2025-07-16 01:59 UTC, disconcision commented on src/web/app/editors/decoration/Deco.re
> +  let warning_view = (id: Id.t) =>
i feel like in principle all the warnings view code should use the same path as the error stuff. basically it should be the same modulo a single top-level css class that you choose to decide whether its styled as an error or a warning. can you see if there's a quick way to combine this with the error equivalent? perhaps just pass a more generic function which take a string to be used as a css class; pass "error" for errors, "warning" for warnings, something like that, put that class on the main div for the errors, then have seperate css rules for each (but leaving common stuff in a shared class). this could probably be done for `warning_term` as well.

this one isn't a big deal if you don't have the time but i think a small refactor could save some code duplication here and in a couple other places

2025-07-16 01:59 UTC, disconcision commented on src/language/statics/Statics.re
> +      let warning: Warning.t = Warning.var_is_unused(co_ctx, name);
to calculate this warning it looks like you need the co_ctx and the name; both of are already captured by the info; you can add this line to Info.derived_pat (you'll need a switch there to to get the name from Var(name)).

I'm think if you do it this way you might not need to thread `~warning` around 20 times in this file.

2025-07-16 01:59 UTC, disconcision commented on src/language/statics/Statics.re
> +    };
what is this? does it serve a functional role in this PR? needs a comment and probably should be in CoCtx not here

2025-07-17 02:45 UTC, lmulcahy21 commented on src/language/statics/Statics.re
> +    };
This is a hack to have terms recognize that their co-context would contain a hole, as we currently don't mark that in the info term (as far as I'm aware). I changed it to be `$hole` such that it can't be made by a user, but let me know if there's a better way to solve this issue of "there's a hole in a term's scope and it needs to know".

2025-07-17 03:39 UTC, lmulcahy21 commented
<img width="515" height="316" alt="image" src="https://github.com/user-attachments/assets/1a08a410-b4ca-443f-bd57-587cd2a60b77" />
@disconcision made the structural changes, only thing left is the `$hole` hack you commented on, see reply + new comment added to describe that code. The only thing left is the color of the holes; I didn't know how to replicate the oklch feature you described about taking the error colors and changing to yellow so hoped you might provide guidance/your ideal colors for that.

2025-07-22 21:09 UTC, disconcision commented on src/language/statics/Statics.re
> +    };
Hmm, I don't immediately follow... could you clarify?

2025-07-22 21:15 UTC, lmulcahy21 commented on src/language/statics/Statics.re
> +    };
The unused variable warnings shouldn't display if the subsequent program contains a hole, since it could be used inside of the hole. In order to check this I am using the co-context map improperly by having hole terms add a "$hole" entry to the co context and having the warning check for this "$hole" entry. If there's a better way to implement this check that'd be ideal, but I used this hack to get it working.

2025-07-22 21:19 UTC, disconcision approved these changes
I tweaked the colors again and factored out the view code duplication i mentioned; please confirm the latter doesn't cause any issues I missed.

Could you update the co-context hole comment with an explanation closer to the one you replied to me with? Other than that. lgtm

2025-07-22 21:24 UTC, lmulcahy21 commented
Will do as soon as I get home, thanks for the feedback and color changes.

2025-07-24 15:22 UTC, merged