Let operators
hazelgrove/hazel pull request #1056
Opened 2023-06-27 20:20 UTC by xzxzlala

2023-07-18 21:45 UTC, disconcision commented
why is the undefined let operator error a dynamic error instead of a static error?

2023-07-19 22:14 UTC, xzxzlala commented
I tried to make the error to be Free Variable.

<img width="535" alt="image" src="https://github.com/hazelgrove/hazel/assets/73332800/9a930fe3-2985-404f-bc75-b88b47d25697">

But then I don't know how to make cursor inspector to indicate the "let-" operator is not defined.

2023-07-30 21:19 UTC, cyrus- commented
Since this is based on the user-defined operators, can you change the base branch of this PR to that branch? There are also potential conflicts that need to be resolved.

2023-07-30 21:27 UTC, cyrus- requested changes
It isn't working correctly when the let+ definition is annotated with a type hole:
<img width="812" alt="image" src="https://github.com/hazelgrove/hazel/assets/280638/7574aeb6-1dde-47a6-946d-c4c98a5e5d20">

2023-07-31 20:00 UTC, cyrus- commented
@xzxzlala see also conflicts with `dev` that need to be resolved.

2023-08-03 18:19 UTC, xzxzlala commented
I merged dev and user-defined-operators(set origin/haz3l-user-defined-operators as upstream).
The annotation bug is a bug of user-defined-operators, I'm still trying to find a solution.

2023-08-18 17:56 UTC, cyrus- commented
Marking as draft pending merge of #828

2024-05-28 02:38 UTC, cyrus- commented
@xzxzlala I think this should be ready to merge -- do you have time to resolve the last merge conflicts?

2024-05-28 13:43 UTC, Negabinary commented
I'm wondering whether it might be good to add a static error as well for undefined let operators, since it can be determined at compile-time whether a let operator is in scope?

2024-05-28 15:58 UTC, Negabinary commented
> I'm wondering whether it might be good to add a static error as well for undefined let operators, since it can be determined at compile-time whether a let operator is in scope?

Sorry I didn't notice Andrew had already brought this up - is there a reason we've gone back to dynamic errors?

2024-05-28 17:58 UTC, cyrus- commented
Oh yeah, I thought that is what we had done but seems it is still a dynamic error. @xzxzlala do you have time to make this a static error?

2024-06-17 12:52 UTC, xzxzlala commented
No problem! 
I could work on it. Sorry for the late reply, I didn't see the message because I had to use VPN to check my Gmail messages.
However, I'm now quite busy with graduation/capstone design. Maybe need more time :)

2026-04-21 12:56 UTC, cyrus- commented
archiving because this is no longer an active effort, but want this in a future PR

2026-04-21 12:56 UTC, closed without merging