Better Indent
hazelgrove/hazel pull request #1099
Opened 2023-08-31 00:34 UTC by disconcision

2023-12-05 01:56 UTC, cyrus- requested changes
@disconcision this looks good to me, just needs a merge in `Code.re`

2023-12-18 00:29 UTC, disconcision commented
@cyrus I've brought this up to date with dev. As we talked about, I have some misgivings about merging this in, due to (a) likely minor but complex-to-reason-about performance hit, (b) debatably confusing behavior when indentation changes with caret movement. As a result, I am ambivalent about whether this should be merged or not, though I do intend to maintain it for now as a reference point.

2024-02-29 05:25 UTC, cyrus- commented
Closing in anticipation of new tylr implementation, will have to revisit this topic.

2025-07-06 23:38 UTC, disconcision commented
Closed in favor of #1761

2025-07-06 23:38 UTC, closed without merging