added IfThenElse to DHExp.t
hazelgrove/hazel pull request #1122
Opened 2023-10-18 17:51 UTC by LarWong

2024-01-11 15:34 UTC, Negabinary approved these changes
lgtm!

2024-01-15 00:39 UTC, cyrus- requested changes

2024-01-15 00:39 UTC, cyrus- commented on src/haz3lcore/dynamics/DH.re
> +      d10 == d20
minor: use `d` variable name prefix for DHExp's only, not the boolean flag

2024-01-15 00:39 UTC, cyrus- commented on src/haz3lcore/dynamics/DH.re
> +    | IfThenElse(bool, t, t, t) // use bool tag to track if branches are consistent
instead of a bool, define a sum type that makes clear what it represents:

```
type consistent = 
  | Consistent
  | Inconsistent
```

2024-01-15 00:39 UTC, cyrus- commented on src/haz3lcore/dynamics/Elaborator.re
> +          DHExp.IfThenElse(false, c', d1, d2)
see above -- the comment seemed to indicate inconsistent should be `true` but it is false here. make sure this is doing what you intend.

2024-01-15 00:39 UTC, cyrus- commented on src/haz3lcore/dynamics/PatternMatch.re
> +  | IfThenElse(_) => DoesNotMatch
elimination forms like if/then/else (and case, prj) should actually be IndetMatch. can you fix that in this PR for all of these?

2024-01-15 00:39 UTC, cyrus- commented on src/haz3lcore/dynamics/PatternMatch.re
> +  | IfThenElse(_) => DoesNotMatch
see above

2024-01-15 00:39 UTC, cyrus- commented on src/haz3lcore/dynamics/PatternMatch.re
> +  | IfThenElse(_) => DoesNotMatch
see above

2024-01-15 00:39 UTC, cyrus- commented on src/haz3lweb/view/dhcode/layout/DHDoc_Exp.re
> +          DHDoc_common.Delim.mk("("),
parenthesization should be handled by the parent expression

2024-01-16 15:14 UTC, Negabinary commented
I've just noticed there's something strange going on with casting on this branch as well
![image](https://github.com/hazelgrove/hazel/assets/31668468/4f768e13-2368-41b6-9e00-00b7a50eefad)

Compared with other branches, the elaboration appears to have an extra `?` cast at the end of the if-then-else block

![image](https://github.com/hazelgrove/hazel/assets/31668468/0a3ea00f-f78e-4e92-a02c-608d6561d238)

I don't know enough about casting to know where that's come from or why it's a problem though

2024-01-23 21:28 UTC, cyrus- commented
@disconcision can you take a look at the cast issue above, ideally today if you can? (we need to release A1 which uses this, I can take a look if not)

2024-01-23 22:03 UTC, disconcision commented
@cyrus- IfThenElse appears to have been added to the 'Normal cases: wrap' section (which gets casts) as opposed to the 'Forms with special ana rules but no particular typing requirements' which includes Case. I've moved it to the latter and that resolves @Negabinary's example above

2024-01-24 03:32 UTC, cyrus- approved these changes

2024-01-24 03:33 UTC, merged