Casting arrow fixes
hazelgrove/hazel pull request #1123
Opened 2023-10-19 04:18 UTC by ruiz-m

Bug #1
When performing uexp_to_info on this expression
![image](https://github.com/hazelgrove/hazel/assets/55409421/b3cd23d0-edaf-4c9a-9e00-8930cb4e9e7b)

The constructor Yo in the function position of the Ap is analyzed with Arrow(Unknown(Internal), Sum["Yo", None]).
In of_ctr_in_ap, the mode given is Arrow(Unknown(Internal), Sum["Yo", None])

When the expression is elaborated

![image](https://github.com/hazelgrove/hazel/assets/55409421/38ab2780-34da-4835-8ea7-3c281b0e685e)

However, when I perform the type assignment. the resulting type is None because the type inside the outer cast is evaluated to be Sum["Yo", None] instead of Unknown(Internal).
This problem seems to be a compatibility issue with the type assignment module.
I initially came up with a solution, but i recently realized that it was not correct.
The current solution works with type assignment, but it may require further discussion.

Bug #2 
Closes #1119

2023-10-30 20:18 UTC, disconcision reviewed
So for the Mode.re changes, these cause the following observable changes in Examples/ADT Statics:

1. a. in dev:
<img width="449" alt="2023-10-30-15-59-firefox_FR4baej5xt" src="https://github.com/hazelgrove/hazel/assets/22436459/365a357c-7757-4905-b9a2-30e6b6f5c45a">
1. b: in casting-arrow-fixes:
<img width="435" alt="2023-10-30-16-00-firefox_6k5golSS3S" src="https://github.com/hazelgrove/hazel/assets/22436459/18296d6f-f8e1-4a38-9900-ff1b6fe878a6">

The reason I instituted the behavior in (a) was to try and make the analytic pseudo-scope for constructors resemble their synthetic scope behavior. Your changes makes it so that nullary constructors defined in a type annotation won't be considered 'in scope' if they are used in their pattern as unary constructors; instead, such uses will be either unbound, or as is the case here, refer to their previous definition. Similarly:

2. a. in dev: 
<img width="461" alt="2023-10-30-15-58-firefox_PhRRwjDDx1" src="https://github.com/hazelgrove/hazel/assets/22436459/d1a8a5bf-e248-406d-9882-5afbb5de9f44">
2. b: in in casting-arrow-fixes: 
<img width="503" alt="2023-10-30-15-59-firefox_XN2KYxEb4i" src="https://github.com/hazelgrove/hazel/assets/22436459/2e230995-f7c0-4b90-9e15-0bb873be2081">

I don't have a strong feeling about this kind of behavior one way or the other... I generally didn't feel great about this special case, but the new behavior feels potentially confusing to me as well. @cyrus- any opinion?

But can you clarify for me exactly what Bug #1 is? I don't totally follow what exactly goes wrong in DHExp type assignment in this case?

Also @ruiz-m can you clarify which changes here are addressing which bug? The first elaborator change is obviously addressing #1119 aka bug 2, and the Mode change bug #1, but I'm not sure about the second elaborator change i.e. changing the FixF type annotation to ty_body? is this actually load-bearing, I didn't think anything was being done with this type?

2023-10-30 21:47 UTC, ruiz-m commented
Based on the example let_ : +Yo = Yo("lol") in, the type assignment module would first take the type of nonempty hole by returning the type that is being analyzed for the empty hole which would be ? -> Sum(["Yo", None]). The type for cast("lol", String, ?) would be ? because "lol" has type String and is casted with no issues. Since the expression in the definition of the let expression is Yo("lol") and Yo has type ? -> Sum(["Yo", None]) and the type inside the parameter is ?, the resulting type of the Ap expression is Sum(["Yo", None]). However, there is a cast outside the Ap expression from ? to Sum["Yo", None] which results in a failed cast because ? and the type of Ap expression is not ?. That particular cast causes the problem and type assignment fails.

2023-11-10 05:26 UTC, cyrus- commented
Marking as draft for now as you work through the details here.

2024-01-31 16:29 UTC, ruiz-m commented
![Screenshot from 2024-01-31 11-28-46](https://github.com/hazelgrove/hazel/assets/55409421/326ecaa8-059a-4dde-9a43-1b6fed03322d)

Demonstration that the unwanted cast is removed with this solution.

2024-01-31 22:53 UTC, disconcision requested changes
I feel like I'm not sold on the changes in error attribution / error messages here, independent of the casting situation. From a consistency perspective all other such errors are attributed to function position, not the application itself; from the user perspective it's not obvious what this is a special case. Same for the error message, which reads as over-specialized (if I wrote `1(2)` it doesn't get an "application of Int type" error).

Also (this is maybe orthogonal) it's odd that when you put the caret on the constructor itself, it claims nothing is wrong:
<img width="462" alt="Screenshot 2024-01-31 at 5 51 19 PM" src="https://github.com/hazelgrove/hazel/assets/22436459/f7e37c85-94c6-4d6e-92e0-a9d5f40dfabe">

@ruiz-m are we sure there isn't a way to resolve the casting issue while keeping the existing attribution in place?

2024-01-31 22:53 UTC, disconcision commented on src/haz3lcore/statics/Statics.re
> +      };
lets split this out into a fn called Self.of_ap

2024-01-31 22:53 UTC, disconcision commented on src/haz3lcore/statics/Statics.re
> +    let self: Self.t =
this can be a call to the same fn as the exp version maybe

2024-01-31 23:15 UTC, ruiz-m commented
@disconcision I will see if there could be another way to resolve the casting issue.

2024-02-10 21:53 UTC, cyrus- approved these changes

2024-02-10 21:54 UTC, disconcision approved these changes

2024-02-10 21:54 UTC, merged