Dynamic layout for inexhaustive case/indeterminately match case
hazelgrove/hazel pull request #1125
Opened 2023-10-22 16:22 UTC by pigumar1

2023-10-23 16:22 UTC, pigumar1 commented on src/haz3lcore/dynamics/Elaborator.re
> +          // TODO: review
Not problematic for now since currently `DHExp.InexhaustiveCase` behaves exactly the same as `DHExp.InconsistentBranches`

2023-11-18 20:37 UTC, cyrus- requested changes
see comment -- I think we can unify the case constructs here rather than implementing a third variant

2023-11-18 20:37 UTC, cyrus- commented on src/haz3lcore/dynamics/DH.re
> +    | InexhaustiveCase(MetaVar.t, HoleInstanceId.t, case)
Instead of having three different case constructs in DHExp, let's merge them into one with an additional flag parameter for when there is an error.

2024-07-25 19:06 UTC, cyrus- commented
@pigumar1 I don't recall the precise purpose of this PR -- what is it and what is the status?

2024-07-27 13:54 UTC, pigumar1 commented
> @pigumar1 I don't recall the precise purpose of this PR -- what is it and what is the status?

@cyrus- I have updated the purpose of this PR at the top. The expected behavior has already been implemented, but some code simplifications can be done, as suggested by the comment above. #1154 was introduced for this code simplification, but it has its own relevant concerns, which are mentioned at the top of that PR.

2026-04-21 12:58 UTC, cyrus- commented
archiving since this is no longer an active project, but thanks for the design @pigumar1 !

2026-04-21 12:58 UTC, closed without merging