Empty hole casting fix
hazelgrove/hazel pull request #1132
Opened 2023-11-05 18:55 UTC by ruiz-m

Bug
Closes #1119

2023-11-10 05:20 UTC, cyrus- requested changes

2023-11-10 05:20 UTC, cyrus- commented on src/haz3lcore/dynamics/Elaborator.re
> +      | Cast(_) => d
this seems like too general of a fix to handle the specific case of empty holes in function position having casts on them. empty holes should always take on the expected type, and in function position that would be ? -> ?.

2024-01-19 01:29 UTC, disconcision approved these changes
@ruiz-m in the original bug report (#1119), and when we talked about it, you thought parentheses were involved here? did that turn out to be a red herring?

anyway I'm fine with this fix, as it's relatively lightweight and solves the issue, but I can't say i'm 100% clear on why this is correct, so it's probably worth planting a few words here or in a comment about the rational.

2024-01-19 01:29 UTC, disconcision commented on src/haz3lcore/dynamics/Elaborator.re
> -      DHExp.cast(d, Unknown(prov), Arrow(Unknown(prov), Unknown(prov)))
let's add a comment here providing an explicit example of why this case is necessary (eg from the issue)

2024-01-19 01:51 UTC, ruiz-m commented
@disconcision yes, the issue turned out to be a combination with SynFun and parentheses
In the bug the parentheses were in the function position of Ap and because of the parentheses it does another cast from ? to ? -> ? when the wrap function is applied. That is why I made the fix in the synfun section of the cast function

2024-02-10 21:22 UTC, cyrus- approved these changes

2024-02-10 21:34 UTC, merged