Implement Labeled Tuples
hazelgrove/hazel pull request #1235
Opened 2024-03-05 04:56 UTC by WondAli

**Goal:** Implement Labeled Tuple functionality into Hazel.
Note: I don't think I can change the source branch on the old pull request. This redesign of the implementation was started on a new branch, so the old pull request (and branch) is outdated.

TODO: Add more detail to the pull request; add more detail about syntax and semantics

**What are Labeled Tuples?**
An element in a tuple can be "labeled" or "named" with the `=` operator. For example, `(x=1, y=2)` is a tuple expression in which its elements are labeled `x` and `y` respectively. These labels are relevant only within their nearest enclosing tuple.
The `=` operator can be thought of as a binary operator that takes in a string and an expression, and returns the expression.

(Uncertain) A labeled element is type-consistent with the type of the element it is labeling.

**Labeled Tuple Features**
When analyzed against a labeled tuple type, the labeled items can be placed anywhere in the tuple expression and tuple type (the unlabeled items must be in relative order to each other). 
- Ex: `(x=1, True, y=6)` is properly typed against `(Bool, y=Int, x=Int)`
- Ex: `Let x=a, y=b = (y=2, x=4)` will bind `4` to `a` and `2` to `b`

**Dot Operators**
The dot operator `.` can be applied to a tuple to extract a labeled element.
For example, `(x=1, 2, 3).x` is equivalent to `1`
Currently undefined for anything except tuple expressions.

**Implementation Strategy**
1. Implement a "label" term to express the labeled tuple element.
2. Modify tuple semantics to consider labeled term contained within the tuple.
3. Implement the dot operator as a new expression that takes an expression and a pattern (var only) 

**Checkpoints:**
- [ ] finish writing the draft pull request
- [x] Implement the Label term that simply wraps an element with a string.
- [x] Tuples type-check assuming all elements are in order.
- [x] Tuples type-check considering rearrangements of labeled elements.
- [ ] Tuple type-checking when there is an unequal number of labeled elements
- [ ] Dot operation on Tuple expressions

**Known Bugs:**
- When let-pair-binding with a variable that holds a labeled tuple, the evaluation does not complete. I believe the error lies somewhere with the new tuple semantics
```
let (x=a, y=b) = (x=1, y=2) in
a // This works as expected, and stepper will evaluate 1 or a=1```
```
```
let v = (x=1, y=2) in
let x=a, y=b = v in // the stepper does substitute v with (x=1, y=2)
a // The stepper does not evaluate to 1, and remains stuck (?)
```

2024-05-01 22:59 UTC, cyrus- commented
@WondAli playing with this branch, looks like the labels aren't showing up in the types of the tuples (and so you get weird run-time errors when projecting out a label that doesn't exist). is there a specific issue with adding labels to product types?

2024-09-13 17:06 UTC, 7h3kk1d commented on src/haz3lcore/LabeledTuple.re
> +type t = string;
Should this type be `label` instead of `LabeledTuple.t`? I believe it's just used for the labels.

2024-09-13 17:06 UTC, 7h3kk1d commented on src/haz3lcore/LabeledTuple.re
> +    | (Some((s1, _)), Some((s2, _))) => String.equal(s1, s2)
_Personal note_: It would be great if we had `map2`  from https://ocaml.janestreet.com/ocaml-core/109.20.00/doc/core/Option.html

2024-09-13 17:06 UTC, 7h3kk1d commented on src/haz3lcore/LabeledTuple.re
> +                       | (Some(s2), _) when v => compare(s1, s2) != 0
I think you can just use `s1 != s2`

2024-09-13 17:06 UTC, 7h3kk1d commented on src/haz3lcore/LabeledTuple.re
> +                | ((Some(s1), _), (Some(s2), _)) => compare(s1, s2) == 0
Same here with `s1 == s2`

2024-09-13 17:06 UTC, 7h3kk1d commented on src/haz3lcore/LabeledTuple.re
> +  (get_label1, get_label2, f, accu, accu_fail, l1, l2) => {
I think these would be slightly easier to read if the types were on the params as opposed to on the function itself. I'm open to other viewpoints on it though.

2024-09-13 17:06 UTC, 7h3kk1d commented on src/haz3lcore/dynamics/DH.re
> +    | TupLabel(t, t)
Unclear to me why this needs to be a `t` and not a `string` for the first param.

2024-09-13 17:06 UTC, 7h3kk1d commented on src/haz3lcore/dynamics/DH.re
> +      LabeledTuple.equal(get_label(d1), get_label(d2))
It's probably easier to just match against `TupLabel(Label(name1)`

2024-09-13 17:07 UTC, 7h3kk1d commented on src/haz3lcore/LabeledTuple.re
> +    | (Some((s1, _)), Some((s2, _))) => String.equal(s1, s2)
This exists in OptUtil

2024-09-13 20:01 UTC, 7h3kk1d commented
Evaluation should continue around:
```
let x : (a=Int, b=String)= (a=1, b=? ) in (x.b, x.a)
```

2024-09-19 17:52 UTC, 7h3kk1d commented
There's another issue with the parsing for type annotations outside lets:
```hazel
((a="Foo", b=8) : (a=String, b=Int))
```


![Screenshot from 2024-09-19 13-50-26](https://github.com/user-attachments/assets/6f3282ce-91bb-426d-a80b-7da8404333d9)

2024-09-27 15:58 UTC, WondAli commented
There is currently no conversion of standalone labeled types to a singleton tuple, so statics checks a singleton tuple expression against a labeled type (which decays to an int)
![Screenshot from 2024-09-27 01-21-26](https://github.com/user-attachments/assets/90a1f4d4-ef76-4890-890d-22a45c5b4e1d)

2024-09-30 14:11 UTC, 7h3kk1d commented
There's some issues with functions. I'm assuming that's also why the elaboration test is failing.

![Screenshot from 2024-09-30 10-10-00](https://github.com/user-attachments/assets/07edde85-43ce-4d5e-9c32-168f9e438842)

2024-10-09 16:03 UTC, 7h3kk1d commented
Self reminder to write tests and validate the function argument patterns like:
```
let fn : (x=Int, b=Int) -> Int = fun (x=a, b=b) ->a
in
fn(b=2,x=1)
```

2024-10-11 17:34 UTC, 7h3kk1d commented
Check to see behaviors without parens

2024-10-11 18:34 UTC, 7h3kk1d commented
There's still some ongoing conversations on what the behavior of singleton labels should be. Especially with:


```hazel
let x : (l=Int) = 8 in x #It's unclear whether we should be ascribing labels onto any term just based off of the type#

```

2024-10-11 18:40 UTC, 7h3kk1d commented
![Screenshot from 2024-10-11 14-39-42](https://github.com/user-attachments/assets/cc805751-16ed-40ef-a015-e8492cdd2615)
The patterns don't work without parens. I think this is a parsing issue.

2024-10-11 18:42 UTC, 7h3kk1d commented
> ![Screenshot from 2024-10-11 14-39-42](https://private-user-images.githubusercontent.com/995429/375857174-cc805751-16ed-40ef-a015-e8492cdd2615.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NzIzMjksIm5iZiI6MTcyODY3MjAyOSwicGF0aCI6Ii85OTU0MjkvMzc1ODU3MTc0LWNjODA1NzUxLTE2ZWQtNDBlZi1hMDE1LWU4NDkyY2RkMjYxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxODQwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTcwMjY5NGUwOWY1NDc1NThiNDY0ZjQxOGNjZWFhZTc3MzJjN2I5ZTczYTQ5YzBiZWUyMTQzYzJhZTFmYjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YHJvR4QqfG09ldss09lnihBClsq4WKEqGdMOe-jhcZM) The patterns don't work without parens. I think this is a parsing issue.

This may be a problem with regular tuples in dev:
```
let x : Int, String = (8,"hello") in x
```

2024-10-14 15:23 UTC, 7h3kk1d commented
TODO test nested dot operators

2024-11-01 16:24 UTC, 7h3kk1d commented on src/haz3lcore/statics/Info.re
> +    switch (status) {
@disconcision do you know if there's a reason we were recalculating the status here?

2024-11-05 19:40 UTC, cyrus- commented
- singleton analytic case for patterns should insert labels
```
let f : (b=Float) -> Float = 
  fun b -> b
in ...
```

- better messages in the cursor inspector for when lifting occurs

2024-11-08 16:00 UTC, 7h3kk1d commented
![Screenshot from 2024-11-08 10-40-51](https://github.com/user-attachments/assets/4351b23e-9598-4ed4-b90b-693ca3d5eb7c)
Here's a first pass on the "better messages in the cursor inspector for when lifting occurs". We need to figure out how we want to represent this all in statics in a more disciplined way.

@WondAli let me know if you also have any ideas. If we move all the lifting/rearranging to statics maybe there's some additional data we can put on the Info.exp that can be used more generally.

2024-11-08 16:02 UTC, 7h3kk1d commented on src/haz3lcore/statics/Statics.re
> +      status: original_info.status,
Copying the status from the inner expression is probably too clever. We may need to have a more principled status for this expression.

2024-11-08 17:02 UTC, 7h3kk1d commented
> * singleton analytic case for patterns should insert labels
> 
> 
> ```
> let f : (b=Float) -> Float = 
>   fun b -> b
> in ...
> ```
> 

@cyrus- I'm working on the pattern case now and I'm running across an issue I'm curious if you have thoughts on. In the following case the `x` pattern is getting expanded to `(a=x)` as it would in the function case so x ends up just being `3`. So I'm kind of unclear how you actually would bind a variable to the singleton labeled tuple.

`let x : (a=Int) = (a=3)`

2024-11-08 18:34 UTC, cyrus- commented
Sorry I don't understand the example, it doesn't have x?

2024-11-08 18:36 UTC, cyrus- commented
Ah I see,  yeah that's awkward. Don't have an immediate solution...

2024-11-08 18:41 UTC, cyrus- commented
Maybe only patterns that are not under an ascription have the lifting behavior? That would also allow you to explicitly bind a 1-tuple when defining a function:

```
let f : (a=Int) -> Int = 
  fun x : (a = Int) -> x.a
```

and

```
let f : (a=Int) -> Int = 
  fun x -> x
```

seems natural enough to me.

2024-11-15 18:40 UTC, 7h3kk1d commented
> Maybe only patterns that are not under an ascription have the lifting behavior? That would also allow you to explicitly bind a 1-tuple when defining a function:
> 

This is implemented in the latest commit.

2024-11-15 20:22 UTC, 7h3kk1d commented on test/Test_Elaboration.re
> +};
There has to be a better way to do this.

2024-11-15 20:24 UTC, 7h3kk1d commented on test/Test_Elaboration.re
>        |> Exp.fresh,
Something in the elaboration for tuples is adding a bunch more casts here

2025-01-09 20:50 UTC, 7h3kk1d commented
```hazel
let y : (a=String, Float, b=Int) = (a="hello", c=1.2, 3) in
```

Bug where we're allowing extra labels. I don't think we want to allow this.

2025-01-23 19:41 UTC, disconcision commented on src/haz3lcore/statics/Info.re
> +    switch (status) {
@7h3kk1d I don't think so, I think I probably just forgot to update this function when I added derived attributes (including status) into the Info record.

2025-01-23 20:50 UTC, 7h3kk1d commented on src/haz3lweb/app/explainthis/ExplainThis.re
> +        // TODO (Anthony): put in a real message
@WondAli I haven't looked at any of this file so it would be good if you double checked to see if anything remains.

2025-01-23 20:52 UTC, 7h3kk1d commented on src/haz3lweb/app/explainthis/data/LabelTerm.re
> +    syntactic_form: [n |> abbreviate |> tpat], // TODO: Fix this
@WondAli

2025-01-24 15:20 UTC, 7h3kk1d commented on src/haz3lcore/dynamics/Transition.re
> +    // print_endline(Exp.show(d));
todo remove

2025-01-24 15:21 UTC, 7h3kk1d commented on src/haz3lcore/dynamics/Unboxing.re
> +    // | (TupLabel(tl), Cast(t, ty1, ty2)) =>
Remove comments

2025-01-24 15:22 UTC, 7h3kk1d commented on src/haz3lcore/statics/Elaborator.re
> +        // Hack for singleton labeled tuples
Maybe motivate this more

2025-01-24 15:22 UTC, 7h3kk1d commented on src/haz3lcore/statics/Elaborator.re
> +      // let elaborated_labeled: list((option(string), DHPat.t)) =
Remove comments

2025-01-24 15:23 UTC, 7h3kk1d commented on src/haz3lcore/statics/MakeTerm.re
> +            // TODO: Other cases to convert to labels
@WondAli is there remaining work here?

2025-01-24 15:25 UTC, 7h3kk1d commented on src/haz3lcore/statics/TermBase.re
> +    // | (_, TupLabel(_, _)) => false
todo

2025-01-24 15:25 UTC, 7h3kk1d commented on src/haz3lweb/app/explainthis/ExplainThis.re
> +            /* TODO The coloring for the syntactic form is sometimes wrong here... */
todo

2025-02-07 22:53 UTC, cyrus- requested changes
- floating point exponential notation isn't working anymore
- see inline comments

2025-02-07 22:53 UTC, cyrus- commented on src/haz3lcore/statics/Statics.re
> +            |> Option.map(((label, value)) => (label, (inferred, value)))
rename from `value`

2025-02-07 22:53 UTC, cyrus- commented on src/haz3lcore/statics/MakeTerm.re
> +        // TODO: Other cases to convert to labels
resolve these

2025-02-07 22:53 UTC, cyrus- commented on src/haz3lcore/zipper/EditorUtil.re
> +  | Label(_)
keep cases together

2025-02-07 22:53 UTC, cyrus- commented on src/haz3lweb/app/explainthis/ExplainThis.re
> +        // TODO (Anthony): put in a real message
remove

2025-02-07 22:53 UTC, cyrus- commented on src/haz3lweb/exercises/SyntaxTest.re
> +  | Dot(u1, u2)
check to make sure label positions are not being recursed into for variable mentions / recursive functions / etc.

2025-02-10 15:27 UTC, 7h3kk1d commented on src/haz3lweb/exercises/SyntaxTest.re
> +  | Dot(u1, u2)
@cyrus- since we don't have the label sort introduced, the variables in label position are still being evaluated:

![Screenshot From 2025-02-10 10-24-37](https://github.com/user-attachments/assets/f993d061-3b1b-44ef-8311-bca2666964e8)


I can try to make these indet, but it's not clear to me that it's preferable to stop dynamics for the expression. If we still allow evaluation I think we want to continue to recurse into the "label position" in SyntaxTest.

2025-02-10 15:28 UTC, 7h3kk1d commented on src/haz3lcore/LabeledTuple.re
> +let rearrange2:
Better name/documentation

2025-02-10 15:55 UTC, 7h3kk1d commented on src/haz3lweb/exercises/SyntaxTest.re
> +  | Dot(u1, u2)
This seems somewhat related to decisions for now evaluation should proceed in non-empty holes https://github.com/hazelgrove/hazel/issues/1497#issuecomment-2640785436.

2025-02-10 16:10 UTC, 7h3kk1d commented
Reminder to regenerate all doc buffers

2025-02-11 14:51 UTC, 7h3kk1d commented on src/haz3lweb/exercises/SyntaxTest.re
> +  | Dot(u1, u2)
I've put everything in label position in multiholes if it's not a label.

2025-02-11 16:52 UTC, cyrus- approved these changes

2025-02-11 16:52 UTC, merged