Polymorphic equal test
hazelgrove/hazel pull request #1267
Opened 2024-04-15 17:12 UTC by GuoDCZ

In progress handling #1252.

2024-04-25 20:23 UTC, cyrus- commented
@GuoDCZ let's better handle functions:

* there should be a static error on an equivalence where either side has arrow type
* there should be a dynamic error if at run-time, either side evaluates to a function or cast to arrow type

2024-04-28 21:06 UTC, GuoDCZ commented
@cyrus- just to make sure I got the idea. 

When we refer to static error, does it mean something like:
![image](https://github.com/hazelgrove/hazel/assets/113280601/3b7d06bd-9cdd-4ffb-93c5-0ef5a2f08dad)
If so, I don't think `Info.t.error_inconsistent` fit our situation. I am thinking about introducing a new synthesis mode `Mode.t.SynEqual`, who raises a new error `Info.t.error_unexpectedArrow` when finding an arrow type. Because it may influence existing code base, IDK if it's OK to do so.

2024-04-29 02:12 UTC, cyrus- commented
Yes. I'm not sure you need a new synthesis mode, but a new error definitely makes sense.

2024-05-28 13:59 UTC, Negabinary commented
I think equality with holes should probably not evaluate - e.g. `2 == ?` should stay as `2 == ?` rather than evaluate with the unknown, because it's possible the unknown will eventually be filled with the number `2`.

2024-05-29 22:58 UTC, GuoDCZ commented
I run into a problem when handling Constructor case. Runtime (dynamic) DHExp.Constructor does not differentiate arrow type constructor and non-arrow type constructor. The current deployment consider DHExp.Constructor as arrow type, and thus always Indet for Constructors.

The current deployment has following behaviors, could I get some notices on which ones are expected.

![image](https://github.com/hazelgrove/hazel/assets/113280601/660f2018-9f51-49f4-9eba-10f24bcf2958)

2024-05-30 04:41 UTC, cyrus- commented
That behavior is fine -- prohibiting comparisons at arrow type is the intended behavior, even if that is a constructor.

2024-05-30 04:43 UTC, cyrus- commented
I think the error when the two sides are not consistent types should be on the == operation in all cases and indicate that the two sides have inconsistent types, a la the following for list literals (and similar for conditionals):
<img width="986" alt="image" src="https://github.com/hazelgrove/hazel/assets/280638/d00ca59b-e70a-4647-a30f-1d4fec5c4c66">

2024-05-30 19:39 UTC, cyrus- commented
Great. Some last polish things:
- change the cursor inspector and ExplainThis system, which currently still uses the phrase "Integer Equality". We should change it to "Structural Equality"
- the error when there is an arrow type should say "Cannot compare arrow types: ty1 -> ty2"
- When there is a runtime comparison between functions there should be a run time error with an error message, not just a stuck term.

2024-06-07 03:55 UTC, GuoDCZ commented
Remaining issue is that I raise Error for every Constructor type, even if it is not an arrow.
![image](https://github.com/hazelgrove/hazel/assets/113280601/c41a93e3-3f0f-44ec-966a-7ac0094017e8)
This is because I don't know how to check if a Constructor is an arrow type dynamically. `DHExp.Constructor` is defined as follows
https://github.com/hazelgrove/hazel/blob/60102ead840d7a5986ad2839d7ba9e2435121c02/src/haz3lcore/dynamics/DH.re#L42
Maybe we can handle #1313 before we forge on Constructor case? We won't like to compare Constructor of different types.

2024-06-12 17:19 UTC, GuoDCZ commented
When comparing types that contain an Arrow in static stages, it results in a dynamic error handled within `Elaborator.re`. However, there is an exception as followings: if the type contains a constructor with Arrow argument, comparing it also requires comparing Arrow, which should not happened. This can only be found out in dynamic stage.
![image](https://github.com/hazelgrove/hazel/assets/113280601/4cc9142f-a572-4dbb-bc58-d76751d2bfd5)

2024-06-12 17:29 UTC, cyrus- commented
We should statically prevent comparison at any sum type where any constructor has an argument that contains an arrow type (recursively including in components of sums and products).

2024-06-12 17:30 UTC, cyrus- commented
We will still need run-time checking as well I suppose, due to polymorphism (we may not know the type it is instantiated with statically), but let's give errors here as early as possible.

2024-06-22 02:17 UTC, GuoDCZ commented
Workflow:
Static Check:
1. Type inconsistency
2. Type containing Arrow 
  - Recursive case: Var, List, Rec, Sum, Prod
Dynamic Check:
3. Type inconsistency 
  - No double check if checked in (1). 
  - Refer to Cast/FailCast
4. Type containing Arrow
  - No double check if checked in (2). 
  - Constructor may not able to access full type (?to be checked)
5. Evaluation
  - Write dedicated comparing function
  - Raise EvaluatorError for Type Inconsistent case
  - Raise EvaluatorError for Type That not allow to compare (or should not be evaled)
  - (No EvaluatorError should be raised if Everything is good.

2024-06-22 23:43 UTC, GuoDCZ commented
Comments for last commit:
- [x] prevent comparison at any sum type where any constructor has an argument that contains an arrow type
- [x] If A static error is found, Transistor will do nothing but `Indet` (to avoid double error msg), otherwise make dynamic checks. Errors are found as early as possible.

Remaining Issues:
1. We may create a ListLit of different types without static/dynamic error. And the following comparison happens. If this is not intended, maybe we should handle it in ListLit?
![image](https://github.com/hazelgrove/hazel/assets/113280601/3c942fe8-15da-46ab-9528-f93e51f12399)
```typescript
let a : ? = 1. in
[1, a] == [1, a]
```
2. In Hazel type keyword is just alias. In DHExp, `Constructor(_) | Ap(Constructor(_),_)` have no access to the original sum type. I don't know how to trace its sum type dynamically if errors are not caught in static phase. e.g. Types hided by holes.
```typescript
type B = +A+B(Int->Int) in
let a : ? = A in
let b : ? = B in
a == b
```
![image](https://github.com/hazelgrove/hazel/assets/113280601/80c5c6b2-f6ec-48c4-bee5-50194d86f375)
Good news are we can proper handle sum types if the types are known in static stage.
3. `IfThenElse` has a similar case when branches types are found and checked in dynamic phase. In case of inconsistency, it use `Indet` instead of an explicit error like I did for Polymorphic Equality. Maybe we should change either one?
```typescript
let a : ? = 2. in
1 == a
```
![image](https://github.com/hazelgrove/hazel/assets/113280601/fa04f302-ad01-4501-8e4f-55fb5b673497)

2024-07-25 18:03 UTC, cyrus- commented
@GuoDCZ the recent merge of #1121 modified elaboration to include the type in the elaborated constructor, so can you update this branch to make use of that to address the issues you identified above? marking as draft until then.

2024-08-13 11:00 UTC, GuoDCZ commented
Remaining type inconsistency checker issue. Can be solved by fixing #1370

2025-03-02 00:13 UTC, cyrus- commented
@GuoDCZ is this ready to review? if so go ahead and click that button

2025-03-03 17:49 UTC, cyrus- commented
@GuoDCZ can you add some unit tests for this functionality

2025-03-03 17:58 UTC, Negabinary requested changes
Playing around I found a statics bug:

`(5 == 3.0): ` doesn't have an error, when I think it should

![image](https://github.com/user-attachments/assets/f517132c-0d32-4e28-9ff6-78c9ae792dd4)

Likewise this message is slightly strange

![image](https://github.com/user-attachments/assets/27a87c6f-5209-40fd-b5de-e864060961bd)

Also to echo Cyrus' comment, iirc you put a lot of effort in to dealing with edge cases (playing around with it now it does feel pretty robust to weird sum constructor/cast situations) it would be helpful if you could add some tests to stop anyone else from later breaking those edge cases.

2025-03-03 17:58 UTC, Negabinary commented on src/haz3lcore/dynamics/DHExp.re
> +  | Fun(_)
can you add a comment explaining why fun is comparable? - or if I'm understanding it right, maybe this function could be named something like is_value?

2025-03-03 17:58 UTC, Negabinary commented on src/haz3lcore/dynamics/Transition.re
> +    | BinOp(Int((Equals | NotEquals) as op), d1, d2) =>
I wonder whether we should rename BinOp(Int(Equals)) to BinOp(Equals) or BinOp(Poly(Equals))

2025-03-03 17:58 UTC, Negabinary commented on src/haz3lcore/dynamics/Transition.re
> +              BinOp(Int(op), d1', d2') |> rewrap,
is there a reason we need to put fully-cast-stripped expressions here? It might be nice if we could keep the inner casts on output.

2025-03-08 03:04 UTC, GuoDCZ commented
I am trying to add a test case. But I get:

```
 Received: `{ term =
  (BinOp ((Int Equals), { term = EmptyHole; annotation = None },
     { term = EmptyHole; annotation = None }));
  annotation = None }'
  ```
  
  where an error of comparing arrow is expected. I am sure this is a static error tested from frontend. Having no idea why It does not appear in testing.

```js
      test_case("Polymorphic equal compare arrow 2", `Quick, () => {
        annotated_tree_test(
          {|let a : +A+B(Int->Int) = in (a == a)|},
          FIError.(
            Exp.(
              bin_op(
                Int(Equals),
                empty_hole(),
                empty_hole(),
                ~ann=
                  Some(
                    FTemp.Typ.(
                      Exp(
                        Common(
                          Inconsistent(
                            CompareArrow(
                              sum([
                                Variant("A", [], None),
                                Variant("B", [], Some(arrow(int(), int()))),
                              ]),
                            ),
                          ),
                        ),
                      )
                    ),
                  ),
              )
            )
          ),
        )
      }),
```

2025-04-21 01:39 UTC, cyrus- commented
@GuoDCZ there are merge conflicts here again -- can you resolve those and ping me and we can try to get this merged asap?

(regarding your question about testing, not immediately sure, maybe take another look at that problem after merge?)

2025-04-21 15:44 UTC, 7h3kk1d commented
@GuoDCZ let me know if you need help with tests. But how is this supposed to work for actual polymorphic values?

![Screenshot From 2025-04-21 11-42-51](https://github.com/user-attachments/assets/c990a423-577c-48f0-b0d8-a62c01500507)

2025-05-20 06:10 UTC, GuoDCZ commented
> @GuoDCZ let me know if you need help with tests. But how is this supposed to work for actual polymorphic values?
> 
> ![Screenshot From 2025-04-21 11-42-51](https://private-user-images.githubusercontent.com/995429/435723302-c990a423-577c-48f0-b0d8-a62c01500507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc3MjE2NTcsIm5iZiI6MTc0NzcyMTM1NywicGF0aCI6Ii85OTU0MjkvNDM1NzIzMzAyLWM5OTBhNDIzLTU3N2MtNDhmMC1iMGQ4LWE2MmMwMTUwMDUwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUyMFQwNjA5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTIwM2VmMTg4ZmFlZTVjNDU4YjVlYjIzYzI5YTAwYTU2NzQ2YzgwZDJjODg0YTRkYjk2YTlmY2Y3NDliYTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-1iSmmZpxSJ_aSy7TVqBgW6UnIJnWgLm1d5GNG2VVPo)

I assume this behavior is intended: we avoid arrow comparison, detected in static stage.

2025-05-21 00:07 UTC, 7h3kk1d commented
> > @GuoDCZ let me know if you need help with tests. But how is this supposed to work for actual polymorphic values?
> > ![Screenshot From 2025-04-21 11-42-51](https://private-user-images.githubusercontent.com/995429/435723302-c990a423-577c-48f0-b0d8-a62c01500507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc3MjE2NTcsIm5iZiI6MTc0NzcyMTM1NywicGF0aCI6Ii85OTU0MjkvNDM1NzIzMzAyLWM5OTBhNDIzLTU3N2MtNDhmMC1iMGQ4LWE2MmMwMTUwMDUwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUyMFQwNjA5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTIwM2VmMTg4ZmFlZTVjNDU4YjVlYjIzYzI5YTAwYTU2NzQ2YzgwZDJjODg0YTRkYjk2YTlmY2Y3NDliYTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-1iSmmZpxSJ_aSy7TVqBgW6UnIJnWgLm1d5GNG2VVPo)
> 
> I assume this behavior is intended: we avoid arrow comparison, detected in static stage.

We're not detecting it in the static stage for type variables though. I would think we should block those the same way we do arrows. Otherwise you get no static errors but still get the dynamic one.

2025-06-09 16:50 UTC, GuoDCZ commented
> > > @GuoDCZ let me know if you need help with tests. But how is this supposed to work for actual polymorphic values?
> > > ![Screenshot From 2025-04-21 11-42-51](https://private-user-images.githubusercontent.com/995429/435723302-c990a423-577c-48f0-b0d8-a62c01500507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc3MjE2NTcsIm5iZiI6MTc0NzcyMTM1NywicGF0aCI6Ii85OTU0MjkvNDM1NzIzMzAyLWM5OTBhNDIzLTU3N2MtNDhmMC1iMGQ4LWE2MmMwMTUwMDUwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUyMFQwNjA5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTIwM2VmMTg4ZmFlZTVjNDU4YjVlYjIzYzI5YTAwYTU2NzQ2YzgwZDJjODg0YTRkYjk2YTlmY2Y3NDliYTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-1iSmmZpxSJ_aSy7TVqBgW6UnIJnWgLm1d5GNG2VVPo)
> > 
> > 
> > I assume this behavior is intended: we avoid arrow comparison, detected in static stage.
> 
> We're not detecting it in the static stage for type variables though. I would think we should block those the same way we do arrows. Otherwise you get no static errors but still get the dynamic one.

I see. So the error only shows up at Dynamic now, but ideally it would be caught statically. If I understand you correctly, we should raise a static error when the type function is specialized with a type like `Bool -> Bool`.

The issue is that the body of the type function `typfun a -> fun x : a -> x == x` has already been type-checked before we specialize it with `foo@<Bool -> Bool>(id)`. So to catch this error statically, we’d either need to:

1. Go back and re-type-check the body once we know the concrete type of a, OR
2. Delay type-checking the body entirely until specialization.

Both options would require non-trivial changes to how `TypFun` work in the static stage. I’m not sure whether it is worth adding it.

2025-06-09 18:01 UTC, 7h3kk1d commented
> I see. So the error only shows up at Dynamic now, but ideally it would be caught statically. If I understand you correctly, we should raise a static error when the type function is specialized with a type like `Bool -> Bool`.
> 
> The issue is that the body of the type function `typfun a -> fun x : a -> x == x` has already been type-checked before we specialize it with `foo@<Bool -> Bool>(id)`. So to catch this error statically, we’d either need to:
> 
>     1. Go back and re-type-check the body once we know the concrete type of a, OR
> 
>     2. Delay type-checking the body entirely until specialization.
> 
> 
> Both options would require non-trivial changes to how `TypFun` work in the static stage. I’m not sure whether it is worth adding it.

I wouldn't go back and typecheck or delay checking until specialization. I think we should just mark the statics as a failure if the operands are type variables after normalization so it would always get a mark even if it works after specialization. @cyrus- might have other thoughts though.

2025-06-09 22:16 UTC, cyrus- commented
Well, some potentially desirable uses of polymorphic equality requires that it work for a statically quantified type, e.g. using polymorphic equality to implement a Set or Dict type.

I'd suggest the semantics be that there is an error if the types involved are definitely arrows or foralls. Otherwise, it works and results in a run-time error if you end up with a function or type function on either side.

2025-06-11 01:10 UTC, GuoDCZ commented
> Well, some potentially desirable uses of polymorphic equality requires that it work for a statically quantified type, e.g. using polymorphic equality to implement a Set or Dict type.
> 
> I'd suggest the semantics be that there is an error if the types involved are definitely arrows or foralls. Otherwise, it works and results in a run-time error if you end up with a function or type function on either side.

Okay, the current behavior seems consistent with the latter one.

2025-06-11 22:35 UTC, cyrus- commented
@GuoDCZ okay, there are a few small merge conflicts now but after that if it's ready for review I can go ahead and do that

2025-06-12 14:33 UTC, GuoDCZ commented
@cyrus- @Negabinary This PR is ready for review

2025-06-29 19:27 UTC, disconcision approved these changes
lgtm pending cleanup and dev merge... one minor issue with probes to fix

2025-06-29 19:27 UTC, disconcision commented on src/web/app/explainthis/ExplainThis.re
> +             | Int(NotEquals) => (int_not_equal, int_neq_exp_coloring_ids) */
commented code

2025-06-29 19:27 UTC, disconcision commented on src/web/app/explainthis/ExplainThis.re
> +             | Int(NotEquals) => (int_not_equal, int_neq_exp_coloring_ids) */
can prob get rid of what this is referencing too

2025-06-29 19:27 UTC, disconcision commented on src/web/app/explainthis/ExplainThisForm.re
> +  | EqualTrue
are these non poly equal cases still live?

2025-06-29 19:27 UTC, disconcision commented on src/menhirParser/Parser.mly
> +    | NOT_EQUAL_FLOAT { FloatOp(NotEquals) }
do we still have float equals as a separate operator?

2025-06-29 19:27 UTC, disconcision commented on src/menhirParser/Lexer.mll
> +    | "!=." { NOT_EQUAL_FLOAT }
is it a considered decision to retain this? float equals has always seemed like a slightly fraught operator semantically.

2025-06-29 19:27 UTC, disconcision commented on src/web/app/explainthis/data/OpExp.re
> +/* let int_eq_exp: form = {
commented code

2025-06-29 19:27 UTC, disconcision commented on src/web/app/explainthis/data/OpExp.re
> +/* let int_equal: group = {
commented code

2025-06-29 19:27 UTC, disconcision commented on src/web/app/inspector/CursorInspector.re
> +        text("with arrow type inside"),
"values of arrow-containing <ty> cannot be compared" might read a little better

2025-06-29 19:27 UTC, disconcision commented on test/Test_Elaboration.re
> +    /* test_case("Inconsistent case statement", `Quick, inconsistent_case), */
commented code

2025-06-29 19:27 UTC, disconcision commented on test/Test_Menhir.re
> +      /* full_parser_test(
commented code

2025-06-29 19:27 UTC, disconcision commented on src/language/dynamics/DHExp.re
> +  | (Probe(_), _)
should treat probes like parens... just compare the expression part

2025-06-29 19:27 UTC, disconcision commented on src/language/dynamics/DHExp.re
> +  // TODO(zhiyao): are we allowed to compare int/sint/nat?
good question... @cyrus- ?

2025-06-29 19:27 UTC, disconcision commented on src/language/dynamics/DHExp.re
> +  // TODO(zhiyao): are we allowed to compare int/sint/nat?
our treatment of e.g. 2 as a float where appropriate seems to clash a bit with our treatment here but i dunno

2025-06-30 20:28 UTC, cyrus- commented on src/language/dynamics/DHExp.re
> +  // TODO(zhiyao): are we allowed to compare int/sint/nat?
no they should be explicitly converted to have the same types for equality to make sense

2025-07-03 02:34 UTC, cyrus- requested changes

2025-07-03 02:34 UTC, cyrus- commented on src/language/dynamics/DHExp.re
> +  | (TupLabel(l1, d1), TupLabel(l2, d2)) =>
check labels for equality here

2025-07-03 02:34 UTC, cyrus- commented on src/language/term/InvalidOperationError.re
> +  | Inconsistent;
see above re:Incomparable

2025-07-03 02:34 UTC, cyrus- commented on src/language/dynamics/DHExp.re
> +let rec ty_consistent = (d1, d2) => {
ty_comparable

2025-07-03 02:34 UTC, cyrus- commented on src/language/dynamics/transition/Transition.re
> +            DynamicErrorHole(BinOp(op, d1, d2) |> rewrap, Inconsistent)
rename this error to Incomparable

2025-07-03 02:34 UTC, cyrus- commented on src/language/dynamics/transition/Transition.re
> +            DynamicErrorHole(BinOp(op, d1, d2) |> rewrap, CompareArrow)
maybe combine with Incomparable

2025-07-03 02:34 UTC, cyrus- commented on src/language/term/InvalidOperationError.re
> +  | Inconsistent => "Error: Inconsistent Type"
update error message to say "Incomparable types"

2025-07-03 02:34 UTC, cyrus- commented on src/language/term/Typ.re
> +let rec has_arrow = (ctx: Ctx.t, typ: t) =>
has_fun

2025-07-03 02:34 UTC, cyrus- commented on src/language/term/Typ.re
> +    switch (Ctx.lookup_alias(ctx, tvar)) {
normalize before calling this function so you don't have to handle these things -- then you don't need a context

2025-07-03 02:34 UTC, cyrus- commented on src/web/app/explainthis/data/OpExp.re
add an example involving a compound type, e.g. a list / tuple

2025-07-03 02:34 UTC, cyrus- commented on src/web/app/inspector/CursorInspector.re
> +        text("values of arrow-containing cannot be compared:"),
values cannot be compared

2025-07-03 02:34 UTC, cyrus- commented on test/evaluator/Test_Evaluator_Poly_Equal.re
> +          "Equal List",
add a positive test

2025-07-03 02:34 UTC, cyrus- commented on test/evaluator/Test_Evaluator_Poly_Equal.re
> +          elaborate(parse_exp("(false, \"\") == (false, \"\")")),
add a negative test

2025-07-03 02:34 UTC, cyrus- commented on test/evaluator/Test_Evaluator_Poly_Equal.re
> +        );
add labeled tuple tests

2025-07-03 02:34 UTC, cyrus- commented on test/evaluator/Test_Evaluator_Poly_Equal.re
> +            elaborate(parse_exp("(fun x -> x) == (fun x -> x)")),
add typfun test

2025-07-22 22:25 UTC, disconcision commented
This will close #1814

2025-07-22 22:53 UTC, merged