Derivation
hazelgrove/hazel pull request #1302
Opened 2024-05-04 18:06 UTC by GuoDCZ

2024-08-20 08:50 UTC, GuoDCZ commented
We are approaching to the polishing stage. Here we list issues/bugs.
- [ ] Improve Error message
  - [ ] Derivation Error inside label dropdown panel. ==> better view?
  - [ ] External Error: how should we handle it?
    - [ ] NoAbbr ==> Exist?
    - [ ] NotAJudgment
    - [ ] EvalOff
    - [ ] EvalFail
    - [ ] EvalPending
    - [ ] EvalIndet
    - [ ] Stepper
    - [ ] NoElab
- [ ] Spelling suggestion exists when not focused
  - Plan A: turn off when blurred
  - Plan B: turn off across all editor
- [ ] Structure Manipulation Error: 
  - [ ] Empty Abbr disturbance
- [ ] UI <== See any

2026-04-25 18:42 UTC, disconcision requested changes
some minor cleanup. no major concerns beyond those already articulated

2026-04-25 18:42 UTC, disconcision commented on package.json
> +    "web-worker": "^1.5.0"
?

2026-04-25 18:42 UTC, disconcision commented on src/menhirParser/Interface.re
> +  print_endline("yet to parse");
rm

2026-04-25 18:42 UTC, disconcision commented on src/util/ListUtil.re
> +let rec fold_left_map =
this exists in List since 4.11

2026-04-25 18:42 UTC, disconcision commented on src/web/app/editors/code/Code.re
> +      | Some(Language.Info.InfoDrv({sort, _})) => Drv(sort)
this feels weird esp as it requires the statics

2026-04-25 18:42 UTC, disconcision commented on src/web/app/editors/code/Code.re
> +      | _ => sort == data.sort
this logic is recapitulated from Sort or DrvSort or something I think... probably worth centralizing... also wondering why this needs dynamic info

2026-04-25 18:42 UTC, disconcision commented on src/web/app/editors/result/EvalResult.re
> +              // TODO(zhiyao): what should display root be consistent with?
seems fine as is

2026-04-25 18:42 UTC, disconcision commented on test/Test_Coverage.re
> +    /* peanut_1a, // TODO(zhiyao) */
TODO

2026-04-25 18:42 UTC, disconcision commented on test/Test_Coverage.re
> +      print_endline("yet to parse indicated exp");
printlns

2026-04-25 18:42 UTC, disconcision commented on test/Test_Grammar.re
> +        // TODO(zhiyao): I might need instructions on how to write this part for derivation term
TODO

2026-04-25 18:42 UTC, disconcision commented on test/Test_ReparseDocSlides.re
> +      print_endline(
rm

2026-04-25 18:42 UTC, disconcision commented on src/haz3lcore/lang/Form.re
> +  /* Autocompletion only fires on sort [Exp], so each Drv form that should be
concerning!

2026-04-25 18:42 UTC, disconcision commented on src/haz3lcore/tiles/Mold.re
> +              /* TODO(zhiyao): I dont know why this happen to some derivation term
TODO. no clue

2026-04-25 18:42 UTC, disconcision commented on src/haz3lcore/tiles/Segment.re
> +  /* NOTE(zhiyao): disclaimer: didn't look into how remolding works*/
TODO.

2026-04-25 18:42 UTC, disconcision commented on src/language/derivation/release_note.tex
> +\section{Hazel Proof Tree System}\label{release-note}
should this be here? some is commented out

2026-04-25 18:42 UTC, disconcision commented on src/web/www/style/nut-menu.css
> +     doesn't show an empty gap to the right of the dropdown when not hovered. */
lmao

2026-04-25 18:42 UTC, disconcision commented on src/web/app/Page.re
> +    let derivation_info = Editors.Model.get_derivation_info(model.editors);
maybe stick this in the scrutinee instead to show its not used out of the switch scope

2026-04-25 18:42 UTC, disconcision commented on src/web/app/editors/Editors.re
> +    ignore(mode_menu);
what is this

2026-04-25 19:00 UTC, disconcision commented
@cyrus- Probe Sidebar is very broken

2026-04-25 23:42 UTC, cyrus- commented
> Probe Sidebar is very broken 

actually broken in `dev` too, but looks like a simple fix so will do that here (can port into dev if this gets further delayed)

2026-04-25 23:44 UTC, cyrus- commented on src/web/app/editors/Editors.re
> +    ignore(mode_menu);
dead code, removed

2026-04-26 00:22 UTC, cyrus- commented on src/web/app/editors/code/Code.re
> +      | Some(Language.Info.InfoDrv({sort, _})) => Drv(sort)
came up with a nice refactor that also allows us to highlight judgements / props differently from expressions which is nice

2026-04-27 10:09 UTC, disconcision approved these changes
lgtm

2026-04-27 11:23 UTC, merged