Adds theorem-in keywords draft
hazelgrove/hazel pull request #1308
Opened 2024-05-07 20:50 UTC by nskh

Replaces https://github.com/hazelgrove/hazel/pull/1263.

In-progress PR to add a theorem keyword in the style of let-equals-in to Hazel.

Based on [stepper-rewrites](https://github.com/hazelgrove/hazel/tree/stepper-rewrites) this time.

2024-05-08 18:02 UTC, Negabinary requested changes

2024-05-08 18:02 UTC, Negabinary commented on src/haz3lcore/dynamics/Elaborator.re
> +      | Theorem(_, _, _) => Some(DHExp.Tuple([]))
we probably want this to elaborate to the in-part of the expression, not just a tuple

2024-05-08 18:02 UTC, Negabinary commented on src/haz3lcore/lang/Precedence.re
> +let theorem_ = 24;
we can probably re-use the precidence that let uses here - we probably don't want a lower precedence than the min

2024-05-08 18:02 UTC, Negabinary commented on src/haz3lcore/statics/Statics.re
> +    add(~self=Just(Prod([])), ~co_ctx=def.co_ctx, m);
this is going to be more like the Seq case now that we've got an `in` - you can pretty much copy seq exactly

2024-05-08 19:02 UTC, nskh commented on src/haz3lcore/lang/Precedence.re
> +let theorem_ = 24;
cool, just use `let_` directly, or do I set `theorem_ = let_`?

2024-05-08 19:04 UTC, nskh commented on src/haz3lcore/dynamics/Elaborator.re
> +      | Theorem(_, _, _) => Some(DHExp.Tuple([]))
makes sense, I wasn't sure what exactly to put here so let's discuss further

2024-05-08 19:08 UTC, nskh commented on src/haz3lcore/statics/Statics.re
> +    add(~self=Just(Prod([])), ~co_ctx=def.co_ctx, m);
cool, and the `e1, e2` are instead `def, body` from the theorem? will update

2024-05-08 21:06 UTC, Negabinary commented on src/haz3lcore/statics/Statics.re
> +    add(~self=Just(Prod([])), ~co_ctx=def.co_ctx, m);
yeah because we're discarding def like how we're discarding e1

2024-05-08 21:06 UTC, Negabinary commented on src/haz3lcore/lang/Precedence.re
> +let theorem_ = 24;
I think you can use `let_` directly

2024-05-22 20:14 UTC, nskh commented on src/haz3lcore/dynamics/Elaborator.re
> +      | Theorem(_, _, _) => Some(DHExp.Tuple([]))
resolved in latest commit

2024-05-22 20:17 UTC, nskh commented
@Negabinary: I addressed your changes, should be ready for review. We can merge as-is, or discuss how to add in some way to invoke a stepper by adding a `proof` keyword here too.

2024-05-22 20:38 UTC, Negabinary approved these changes

2024-05-24 14:39 UTC, cyrus- commented
```
theorem name = typ 
proof "serialized stepper data" 
in e

things we need in the typ syntax:

forall x -> ty
exists x : T -> typ.  [sigma types]
(x : typ) -> typ. [pi types]
   (syntactic sugar: forall x : T -> ty)
typ(typ). 
e1 = e2.  [equality types]
```

2024-05-28 17:29 UTC, cyrus- commented
If we do the syntax as:

```
theorem name : typ 
proof e1
in e2
```

then this becomes just another let expression exactly -- that should be pretty straightforward to do so let's update this PR in that direction, then make another PR for adding the new type forms.

2024-07-08 21:43 UTC, cyrus- commented
TODO:

- change sorting to `theorem pat = exp in exp`, which matches let expressions exactly
- have theorem behave exactly like a let expression everywhere else in the codebase
- at the type level, rename existing `forall` to `type` 
- add new `forall pat -> ty` construct to types
- add `{e1 = e2}` form to types

2026-04-21 13:48 UTC, closed without merging