Construct sexp
hazelgrove/hazel pull request #1328
Opened 2024-07-17 01:21 UTC by gcrois

This branch seeks to add functionality to generate an [sexp](https://github.com/janestreet/sexplib) from valid Hazel code in the file [`src/haz3lweb/SexpConversion.re`](https://github.com/hazelgrove/hazel/blob/construct_sexp/src/haz3lweb/SexpConversion.re).

- [x] Triv
- [x] Bool
- [x] Int
- [x] Float
- [x] String
- [x] ListLit
- [ ] Invalid
- [ ] EmptyHole
- [ ] MultiHole
- [ ] Constructor
- [ ] Fun
- [ ] Tuple
- [ ] Var
- [ ] Let
- [ ] TyAlias
- [ ] Ap
- [ ] If
- [ ] Seq
- [ ] Test
- [ ] Parens
- [ ] Cons
- [ ] ListConcat
- [ ] UnOp
- [ ] BinOp
- [ ] Match

2024-07-19 14:05 UTC, gcrois commented
Remaining: finish `sexp_of_uexp`, build test cases

2024-07-25 18:56 UTC, cyrus- requested changes
reviewed the `go` functions

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | MultiHole(_) => Atom("Not implemented")
this can be "(multihole ...)" for completion.

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +      List([Atom("let"), List([go(exp1), go(exp2)]), goUPat(pat)])
the pattern should go first, then exp1 and then next to it (not nested) exp2

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | ListConcat(list1, list2) => List([Atom("@"), go(list1), go(list2)])
maybe `concat` to be consistent with us using `cons` rather than `::`

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | EmptyHole => Atom("?")
@disconcision do we want to use `?` or `??` for empty holes?

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | MultiHole(_) => Atom("Not implemented")
see above

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | TypeAnn(pat, typ) => List([goUPat(pat), goTyp(typ)])
need to do something here to indicate it is a type annotation, maybe `(: p ty)`

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | EmptyHole => Atom("?")
see above

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | MultiHole(_) => Atom("Not implemented")
see above

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | EmptyHole => Atom("EmptyHole")
use `?`/`??` as above

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | MultiHole(_) => Atom("MultiHole")
see above

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | Sum(_list) => Atom("list") //List([Sexp.Atom("sum")] @ List.map(goTyp, list))
need to add support for sum types (algebraic data types)

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | Arrow(_, _) => Atom("Arrow")
need to add support for arrow types

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | Parens(_) => Atom("Parens")
just recurse down as in the other parens cases

2024-07-25 18:56 UTC, cyrus- commented on src/haz3lweb/SexpConversion.re
> +    | Ap(_, _) => Atom("Ap")
treat the same as other ap cases

2026-04-21 13:03 UTC, cyrus- commented
archiving

2026-04-21 13:03 UTC, closed without merging