Fix source maps
hazelgrove/hazel pull request #1356
Opened 2024-08-06 14:26 UTC by 7h3kk1d

![image](https://github.com/user-attachments/assets/ff4d835e-c7ba-40b1-98f6-7383e208cad8)

Sets up source maps in dev so you can get actual line numbers/debugging in stack traces

2024-08-06 15:02 UTC, 7h3kk1d commented on src/haz3lcore/dune
> +  (flags :standard --debuginfo --noinline --dynlink --linkall --sourcemap))
Try going back to the profiles

2024-08-06 15:41 UTC, 7h3kk1d commented on src/haz3lcore/dune
> +  (flags :standard --debuginfo --noinline --dynlink --linkall --sourcemap))
The rules didn't work so I set it on the env

2024-08-09 00:03 UTC, cyrus- requested changes
Seems to work for me! Haven't robustly tested but breakpoints and exceptions seem to correctly work, which is huge.

There is a section on Source Maps in `README.md` in the root directory that needs to be updated. 

Can you also include these flags in the `dune` files in the other top-level libraries (`pretty`, `haz3lschool`)?

2024-08-09 01:08 UTC, disconcision approved these changes
works for me!

2024-08-10 00:18 UTC, cyrus- approved these changes

2024-08-10 00:18 UTC, merged