Num underscore
hazelgrove/hazel pull request #232
Opened 2020-05-06 05:29 UTC by Yunif3

**Allowed underscore to be a part of IntLit and FloatLit**
**resolves #231 and resolves #129 **
 
- "_" has no effect on the value of IntLit and FloatLit
- "_" has no effect on the maximum number of digits of IntLit and FloatLit
- `[int|float]_of_string` fails when there is an underscore, so a new helper function called `StringUtil.strip_underscores` was introduced to remove underscores in `TextShape.of_text` function and `syn_expand_operand` in `Dynamics.re`

2020-05-07 03:48 UTC, cyrus- requested changes
few code cleanup things needed

2020-05-07 03:48 UTC, cyrus- commented on src/hazelcore/semantics/dynamics/Dynamics.re
> +      let stripped_n = StringUtil.strip_underscores(n);
logic for converting the string argument of IntLit/FloatLit to an OCaml int/float should be in refactored into a helper function in TextShape, not repeated any time its needed.

2020-05-07 03:48 UTC, cyrus- commented on src/hazelcore/util/StringUtil.re
> +  let rec helper = (index: int, stripped: string): string =>
There is likely a more efficient way using standard library functions to drop a single character.

2020-05-07 03:48 UTC, cyrus- commented on src/hazelcore/semantics/TextShape.re
> +  let stripped_text = StringUtil.strip_underscores(text);
see comment below

2020-05-07 03:50 UTC, cyrus- commented
you could have automatic comma insertion in long number literals be part of the pretty printing logic in Hazel rather than or in addition to adding support for underscore...

2020-05-08 02:47 UTC, Yunif3 commented
we could replace underscores in Int/FloatLit with something else in pretty printing logic, but this also fixes "_1" being currently being recognized as Float in Dev. 
Do you suggest making a separate fix for this (i.e. not allowing the input of a number after _"? @cyrus-

2020-05-08 03:29 UTC, cyrus- commented
let's go ahead and add the _ support for int/float literals and punt on auto-commas for now.

2020-05-15 23:52 UTC, cyrus- requested changes

2020-05-15 23:52 UTC, cyrus- commented on src/hazelcore/semantics/TextShape.re
> +    StringUtil.num_leading_zeros(stripped_text)
not sure I understand why we have these checks related to the length here... can you clarify in a comment? what is an example of a situation where int_of_string_opt returns Some(0) but this check fails and the function returns None?

2020-05-15 23:52 UTC, cyrus- commented on src/hazelcore/semantics/TextShape.re
>    | (Some(n), _, _, _) when n == 0 =>
you don't need "when n == 0", you can just match on "Some(0)", though I'm not entirely sure why 0 is special cased like this?

2020-05-15 23:52 UTC, cyrus- commented on src/hazelcore/semantics/TextShape.re
> +    StringUtil.num_leading_zeros(stripped_text)
same here, why are we special casing these things? can you provide examples of text that goes into each branch in comments?

2020-05-17 03:09 UTC, cyrus- commented
@Yunif3 you're behind `dev`, please make sure you're up-to-date with `dev` before requesting review

2020-05-18 01:45 UTC, cyrus- commented
@Yunif3 still need you to get this caught up with `dev`, it is currently 107 commits behind. should be a simple `git merge dev` after you pull.

2020-05-18 01:50 UTC, cyrus- commented
@Yunif3 wasn't the plan to support all of OCaml's syntax for floats and ints other than prefix "_"?

2020-05-18 01:53 UTC, cyrus- commented
Oh I see, it sort of works but you can't actually type "0b1111" and things like that because "0b" is not valid. Same with scientific notation, you can't type "e" because there is nothing after the "e" at that moment...

2020-05-18 01:56 UTC, Yunif3 commented
Yes, I didn't add support for binary, octal, and hexadecimal. Do you think it's something that we want right now? Also, many of these problems will be probably solved once the InvalidVar is introduced to replace None in `of_shape` function

2020-05-18 01:58 UTC, cyrus- commented
it does actually support those notations now in your branch as long as you put them in between existing digits, e.g. you can type `b` when your cursor is at `1|1`. yes, I think we need to get InvalidVar support working, so I'll go ahead and merge this for now. @nwilsonj, what's the status of invalidliterals?

2020-05-18 01:58 UTC, cyrus- approved these changes

2020-05-18 01:59 UTC, merged