Invalid text
hazelgrove/hazel pull request #270
Opened 2020-05-22 00:19 UTC by nj-wilson

Implement InvalidText, as a fall-through return of TextShape.of_text.
Refactors uses of TextShape.of_text as it is no longer an option type.

Additionally add an InvalidText form to UHExp.
Differentiate between invalid variables (starts with `a-zA-Z_`) from invalid number literals (starts with `0-9.`).

2020-06-02 01:15 UTC, nj-wilson commented
Currently, have a couple issues:

If I have invalid text in the function position, it currently uses `Got inconsistent type ▶ assumed`. I am not sure if it's intended that it say something akin to `Got invalid text type ▶ assumed`, as well as not being quite sure how to work that into the current BinOp Space handling.

Can only type a single character to reach invalid text, and then it results in a failed action afterward. ie, I can type `3a` , but attempting to type past that is a failed action (of which I do not know what specific `Failed;` it is hitting). I am not sure if this is fine for expected behavior, or to allow typing past that.
I can, however, type something like `342234.2341`, and insert a letter midway, making it invalid text `3422a34.2341`. The same issue occurs with the letter added.

2020-06-02 06:14 UTC, cyrus- commented
It shouldn't say inconsistent type, since InvalidText has hole type. It should say "Got invalid text > matched to" in the same way that free variables do. Check out the code for how free variables are handled.

We should support typing past the first character.

2020-06-09 20:06 UTC, cyrus- requested changes
need to disable ligatures: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures

2020-06-09 23:15 UTC, cyrus- commented
looks like unicode `⇒` is available in the font we use -- I tried changing UHDoc/DHDoc to use but it messes up cursor positioning. seems it is still being treated as 2 characters. is this an easy fix? @dmoon1221

2020-06-09 23:19 UTC, cyrus- commented
it's not actually treating it as 2 character, but it seems to be rendering wider than a normal character. is this an issue with the font?

2020-06-10 00:09 UTC, nj-wilson commented
I'm wondering if it's the font, as if I switch to DejaVu Sans Mono, to looks correct. I'm wondering if Fira Code is just missing that symbol specifically or it's just not rendering correctly.
In Firefox, if I check the computed styling of the span with the arrow, it shows it using "Segoe UI Symbol" instead of Fira Code (Chrome says it's still Fira Code, so I'm not sure).

2020-06-10 00:11 UTC, cyrus- commented
yeah that's probably the issue. I think turning ligatures on for delims is working fine though, so let's just go with that for now.

2020-06-14 04:30 UTC, cyrus- commented
merge conflicts need to be resolved

2020-06-16 18:32 UTC, cyrus- commented
need to implement splitting

2020-06-17 01:09 UTC, cyrus- commented
OK, seems to work. 

In `dev`, I can't press `.` to start constructing a float lit because the dot by itself is not valid. This should be possible now that we have invalid text. Can you add support for that to this branch, @nj-wilson?

2020-06-17 02:47 UTC, nj-wilson commented
I mistakenly set the commit message wrong, I mean to say that inputting a `.` will indeed work as a float, assuming it's properly formed after the `.` of course.

2020-06-18 17:31 UTC, cyrus- commented
We should treat InvalidText like other non-empty holes, so they should have a hole number and be part of the tab order.

2020-06-29 19:04 UTC, cyrus- commented
@nj-wilson looks like there are some merge conflicts with dev

2020-06-29 20:33 UTC, nj-wilson commented
I have fixed the conflicts, though it did point on something I'm not sure if I have correct.
In `holes_operand` in say `CursorPath_Exp`, I was pretty much just mimicking what `EmptyHole` was doing (though with the recent dev merge, I do have `is_empty = false`.

2020-06-30 16:53 UTC, cyrus- requested changes

2020-06-30 16:53 UTC, cyrus- commented on src/hazelcore/CursorPath_Exp.re
>          Some({
is_empty should be false when its InvalidText (check everywhere)

2020-06-30 16:53 UTC, cyrus- commented on src/hazelcore/CursorPath_Pat.re
>          Some({
see above

2020-06-30 16:54 UTC, cyrus- commented
hole numbering looks good to me

2020-06-30 19:01 UTC, cyrus- approved these changes

2020-06-30 19:01 UTC, merged

2020-06-30 19:04 UTC, cyrus- commented
@Yuning30 now that we have invalid text at the level of expressions and patterns, you should add support for the same in your type variable branch