Split Dynamics.re
hazelgrove/hazel pull request #306
Opened 2020-06-03 15:02 UTC by annie-anna

Split Dynamics.re into Expansion.re and Evaluation.re

2020-06-08 06:33 UTC, cyrus- requested changes

2020-06-08 06:33 UTC, cyrus- commented on src/hazelcore/dynamics/Evaluation.re
> +module Evaluator = {
we don't need a submodule here, just call this file Evaluator.re

2020-06-08 23:52 UTC, dmoon1221 commented
One is called `Expansion`, the other is called `Evaluator`? Should we standardize on a noun form, i.e., rename to one to `Expander` or other to `Evaluation`? I think it would also make sense to split `Statics` into `Typechecking`/`Typechecker` and `HoleFixing`/`HoleFixer`.

2020-06-09 01:20 UTC, cyrus- commented
let's call it "Expander" and "Evaluator".

regarding hole fixing being its own module, I think it makes more sense as part of Statics -- it behaves the same as the type checker, except it outputs a hole fixed version of the program (in other words it marks the errors, the way a "production" type checker would). if you want to propose it still, go ahead and make a separate issue and we can discuss there.

2020-06-09 01:20 UTC, cyrus- commented
actually, while we're at it, let's rename "Expansion" to "Elaboration" in prep for eventually merging in livelits. also its called elaboration in the POPL 19 paper anyway.

2020-06-09 13:43 UTC, annie-anna commented
Do I need to rename ``ExpandingKeyword.re`` to ``ElaboratingKeyword.re`` and ``expand`` to ``elab`` in ``PaletteDefinition.re``, too?

2020-06-09 14:07 UTC, dmoon1221 commented
No, those should stay the same

2020-06-09 14:47 UTC, annie-anna commented
Should ``ExpandResult``, ``DoesNotExpand``, ``Expands``, ``UHTyp.expand`` still be the same?

2020-06-09 14:50 UTC, dmoon1221 commented
`UHTyp.expand` should remain the same, the others should be renamed to `ElaborationResult`, `DoesNotElaborate`, `Elaborates`

2020-06-10 14:25 UTC, cyrus- approved these changes

2020-06-10 14:26 UTC, merged