Fix #353 Cleanup Program.move_to_* to return the action only
hazelgrove/hazel pull request #398
Opened 2020-07-15 05:37 UTC by wlitwin

This commit changes the two functions move_to_hole and
move_to_case_branch in Program.re to return the action to be performed
and instead of the new program. The corresponding callers have been
updated as well (only one each in Model.re).

2020-07-29 14:25 UTC, dm0n3y requested changes
Looks good, thanks! Just need to update some documentation.

2020-07-29 14:25 UTC, dmoon1221 commented on src/hazelweb/model/Program.rei
> +let move_to_case_branch: (CursorPath_common.steps, int) => Action_common.t;
need to update documentation

2020-08-10 05:36 UTC, wlitwin commented on src/hazelweb/model/Program.rei
> +let move_to_case_branch: (CursorPath_common.steps, int) => Action_common.t;
Fixed.

2020-08-24 22:28 UTC, dm0n3y approved these changes

2020-08-24 22:28 UTC, merged