make Panel a widget
hazelgrove/hazel pull request #417
Opened 2020-08-05 14:21 UTC by PPER

#371

2020-08-05 21:07 UTC, dmoon1221 commented on src/hazelweb/gui/Panel.re
> +        [Attr.id(id), Attr.classes(["panel"] @ classes)],
Cons `"panel"` instead of appending

2020-08-05 21:07 UTC, dmoon1221 commented on src/hazelweb/gui/Panel.re
> +        [Attr.classes(["panel"] @ classes)],
same here

2020-08-05 21:08 UTC, dm0n3y requested changes
Cursor inspector should also use `Panel`, looks good otherwise

2021-01-13 04:29 UTC, cyrus- commented
@PPER Marking as draft pending small fixes @dmoon1221 identified above.

2022-02-21 06:04 UTC, cyrus- commented
@disconcision @hannahpotter is this useful for you as you add / mess with the sidebar architecture at all? if not we can close.

2022-05-23 18:17 UTC, cyrus- commented
haven't heard back, closing

2022-05-23 18:17 UTC, closed without merging