Type Variables (3)
hazelgrove/hazel pull request #478
Opened 2021-03-04 01:03 UTC by bkase

2021-07-09 03:14 UTC, cyrus- commented
@bkase is the intention still to merge this before the type aliases PR or is this superceded now?

2021-07-10 18:36 UTC, bkase commented
> @bkase is the intention still to merge this before the type aliases PR or is this superceded now?

I figure it's good to merge this if it's good as is so there's not more conflicts just in case it takes a bit to resolve the remaining item on type-aliases

2021-09-27 22:11 UTC, cyrus- requested changes
Can't use type operators anymore, e.g. pressing `>` to create an arrow type no longer works.

2021-09-27 22:12 UTC, cyrus- commented
Also need to get up to date with a few recent dev commits.

2021-10-26 08:16 UTC, dedbox commented on src/hazelcore/Elaborator_Typ.re
> +    switch (k1, k2) {
When I press ">" on a type hole, the type of the operation is consistent (i.e., neither call to ana_skel returned None) but the kinds of k1 and k2 are both KHole. In this case, syn_skel should succeed.

2021-10-26 08:17 UTC, dedbox commented on src/hazelcore/Elaborator_Typ.re
> +    switch (k1, k2) {
The same is true when I press "," on a type hole, which is handled similarly in the preceding case.

2021-11-01 19:43 UTC, cyrus- commented
Closing this PR -- we are folding this into the type alias PR.

2021-11-01 19:43 UTC, closed without merging