Update function syntax from `λx.{...}` to `fun x {...}`
hazelgrove/hazel pull request #502
Opened 2021-05-04 15:47 UTC by minchingtonak

Pretty self-explanatory, all necessary features are implemented.

The only other thing I want to do is move common textual representations for Hazel constructs to their own file so that there aren't duplicated magic string literals at a couple points in the code base. I've done it just for function syntax (see `Doc_common.re`, `DHDoc_common.re`, `UHDoc_common.re` for defs and usage) but I think it would be a good idea to move all of the syntax over to `Doc_common.re`. That's probably best left for a separate PR, but please let me know if you think I should include it in this PR.

2021-09-27 21:56 UTC, cyrus- requested changes
looking close, but needs to be brought up to date with dev in a big way

2021-09-27 21:56 UTC, cyrus- commented on src/hazelcore/Action_Exp.re
> +  | Lam => Construct(SLam)
Let's call it "Fun" instead of "Lam" given the concrete syntax

2021-09-27 21:56 UTC, cyrus- commented on src/hazelweb/layout/Doc_common.re
> +  let sym_Lam = "fun";
Fun here too

2021-11-03 04:29 UTC, cyrus- commented
@minchingtonak do you want to try to wrap this up? looks quite close -- just a few changes above, plus merging in the latest `dev` changes.

2021-11-03 15:29 UTC, minchingtonak commented
Yep, thanks for the reminder! I'll start this today.

2021-11-03 17:35 UTC, minchingtonak commented
I refactored Lam to Fun in ExpandingKeyword.t and Action.t. I'm not sure whether you want me to change Action.t so I can rool that back if need be. I also changed the string constants from Lam -> Fun in Doc, DHDoc, and UHDdoc files.

2021-11-05 17:32 UTC, cyrus- approved these changes

2021-11-05 17:35 UTC, cyrus- requested changes
Whoops, one last late-breaking change needed now that we have Hannah's work on the strategy guide working -- the entries for creating function literals should say `fun ` in addition to `\`.

2021-11-05 17:36 UTC, cyrus- commented
![Screenshot from 2021-11-05 13-36-06](https://user-images.githubusercontent.com/280638/140554211-a4b388d4-9d53-402b-8772-4aac1dabf78f.png)

2022-02-21 05:54 UTC, cyrus- requested changes
Looks great. One last issue: the undo history leaves a "insert var: fun" entry after pressing space, whereas with other keywords like "let" and "case" it overrides the previous entry.

2022-03-29 17:09 UTC, cyrus- requested changes
Just a few last code cleanups and this looks good to go!

2022-03-29 17:09 UTC, cyrus- commented on src/hazelcore/Statics_Exp.re
> +          switch (Var.is_let(x), Var.is_case(x), Var.is_fun(x)) {
Lets use ExpandingKeyword.mk here so there is only one place we need to modify when there is a new keyword added to the system

2022-03-29 17:09 UTC, cyrus- commented on src/hazelcore/Var.re
> +let is_keyword = s => is_let(s) || is_fun(s) || is_case(s);
Let's change this to use ExpandingKeyword.mk -- same goal, to have it so we don't need to find multiple places in the codebase to change when a new keyword is added

2022-03-29 17:09 UTC, cyrus- commented on src/hazelweb/layout/DHDoc_Util.re
> +  let open_Fun = mk(".{");
this is inconsistent with the UHExp pretty printing -- no dot there

2022-03-30 01:23 UTC, cyrus- approved these changes
Looks great!

2022-03-30 01:24 UTC, merged