Examples cardstack + cardstack UI refresh
hazelgrove/hazel pull request #513
Opened 2021-06-21 06:15 UTC by disconcision

This does three things, all aimed at decluttering the main panel.

1. Examples are now a cardstack. Performance-oriented examples are now in a separate cardstack.
2. All cardstack controls are moved to the top bar. This includes the cardstack dropdown, a new card selection dropdown (replacing the examples dropdown), and the next/prev card buttons
3. Ctrl-S now serializes the program to the console; the button is gone.

<img width="594" alt="Screen Shot 2021-06-21 at 2 13 28 AM" src="https://user-images.githubusercontent.com/22436459/122715108-6507a980-d236-11eb-954f-cf5ea7b43000.png">

<img width="594" alt="Screen Shot 2021-06-21 at 2 14 08 AM" src="https://user-images.githubusercontent.com/22436459/122715143-70f36b80-d236-11eb-91b3-d97caea7b3c9.png">

2021-06-21 20:55 UTC, cyrus- commented
Looks great overall. Let's keep the "serialize to console" discoverable somewhere though -- if not where it was, then maybe under the "Options" section of the sidebar (which I think needs to be in a proper sidebar box with a scrollbar)?

2021-06-21 20:56 UTC, cyrus- requested changes
Looks great overall. Let's keep the "serialize to console" discoverable somewhere though -- if not where it was, then maybe under the "Options" section of the sidebar (which I think needs to be in a proper sidebar box with a scrollbar)?

2021-06-21 21:08 UTC, disconcision commented
@cyrus hmm options seems like a bit of a weird location for it, given that it's all toggles for persistent settings... I guess my perspective was that since it's purely a dev feature, discoverability was a negative. But sure I could add a dev tools menu next to options maybe?

2021-06-21 21:09 UTC, cyrus- commented
Yeah we could separate out "options" from "debug / dev tools" stuff, they're both kind of together right now. And on the discoverability thing -- our main users are undergrads working on Hazel right now, so we might as well accommodate in the UI for now. This will of course change as time goes on. :)

2021-06-21 21:12 UTC, cyrus- commented
May want to coordinate with @hannahpotter on the sidebar stuff in a separate PR -- she's been tweaking sidebar layout in her branch.

2021-06-21 21:16 UTC, disconcision commented
I may be biased on the discoverability issue, as giant buttons in the middle of the page are completely invisible to me after my first couple times using a thing, and I ended up implementing my own dump program to console feature before discovering the button :)

2021-06-23 03:03 UTC, disconcision commented
@cyrus i added a top-level actions menu (currently just serialize-to-console):

<img width="519" alt="Screen Shot 2021-06-22 at 10 53 20 PM" src="https://user-images.githubusercontent.com/22436459/123028472-64455380-d3ad-11eb-8cff-70b1dc9a0e7f.png">

Another approach I'd like to consider is just making the hazel logotext itself the menu trigger (retaining the hamburger icon). The idea here is that this could eventually become the 'start button' for a structural command pallette, i.e hitting the logo or pressing a keyboard shortcut would open a structural command line, covering the top bar, where all user-facing model actions could be performed in an assisted fashion

2021-06-23 17:48 UTC, cyrus- commented
Calling it "Actions" is a bit confusing since we use that word for a broader set of things. I'm fine with having a hamburger menu like that for miscellaneous things though -- maybe stick it on the right of the top bar?

2021-06-23 17:48 UTC, cyrus- commented
(If we generalize it as you describe, which sounds cool, then it might be reasonable to call it "Actions" again)

2021-06-23 23:43 UTC, disconcision commented
Okay menu is on the right now:
<img width="1013" alt="Screen Shot 2021-06-23 at 7 18 40 PM" src="https://user-images.githubusercontent.com/22436459/123181402-3f0f1e80-d45b-11eb-9125-1af27e78fc0e.png">

2021-06-28 22:07 UTC, disconcision commented
Just pointing out that this closes #397

2021-06-29 02:08 UTC, cyrus- approved these changes

2021-06-29 02:09 UTC, merged