move Elaborator_Exp.matches to Evaluator
hazelgrove/hazel pull request #524
Opened 2021-07-06 07:42 UTC by dedbox

A simple patch to take the `matches` function out of Elaborator_Exp.ml and put it into Evaluator.ml, the only module that uses it.

2021-07-06 17:16 UTC, cyrus- requested changes
Looks good -- can you add subst to this as well (and check for other pieces with a similar problem)? I don't believe that is used in elaboration either.

2021-07-08 19:14 UTC, dedbox commented
Ok, I've moved subst, subst_var, and id_env to Environment.ml. They're all used by the same modules: Elaborator_Exp and Evaluator.

2021-07-08 20:19 UTC, cyrus- requested changes
looks good, just one more cleanup thing

2021-07-08 20:19 UTC, cyrus- commented on src/hazelweb/model/Program.re
>  let expand =
this should be renamed to elaborate (similarly for other uses of "expand" / "expansion")

2021-07-09 01:27 UTC, cyrus- commented
doesn't compile

2021-07-20 22:55 UTC, cyrus- commented on src/hazelcore/dynamics/Elaborator_Exp.re
>    | LinesExpand(DHExp.t => DHExp.t, Contexts.t, Delta.t)
rename to LinesElaborate / DoNotElaborate

there may be some other uses of Expand in hazelcore/dynamics that need the same treatment

2021-07-20 22:57 UTC, cyrus- requested changes
need a few more renames from expand to elab in hazelcore/dynamics and any part of hazelweb that interfaces with it, but otherwise looks good!

2021-08-11 21:48 UTC, dedbox commented
Ok, I did some more renaming. I did a project-wide search for "xpan", then renamed everything related to elaboration, i.e., not keyword expansion or the inverse of type contraction.

2021-08-11 23:07 UTC, cyrus- requested changes
looks good -- see one comment

2021-08-11 23:07 UTC, cyrus- commented on src/hazelcore/dynamics/Environment.re
> +let subst = (env: t, d: DHExp.t): DHExp.t =>
substitution stuff should be in Evaluator or in a separate Subst module, not part of Environment

2021-09-13 23:55 UTC, cyrus- commented
@dedbox can you fix the issue above so we can get this merged?

2021-09-14 19:13 UTC, cyrus- approved these changes

2021-09-14 19:13 UTC, merged