Make string CommentLine reflect keyboard input
hazelgrove/hazel pull request #531
Opened 2021-07-26 04:01 UTC by zhixiangteoh

Currently, CommentLine only allows `SChar` construction.

Goal of this PR is to make string CommentLine reflect exactly keyboard input, to achieve the following (as example):
- ``# Abl3 to +ype any symb0! 100.89*% ( [ ) ] \ = -_ '~"hello" ; let := >< ?? // $ ^& @hazel \` ``

2021-09-13 23:50 UTC, cyrus- commented
@zhixiangteoh status of this?

2021-09-14 02:26 UTC, zhixiangteoh commented
alt/opt-modified keys “bug” seems most likely related to lack of ocaml support for unicode/utf8—e.g., typing `å` and logging `evt##.key` gives `"å”`, but logging `Key.get_key(evt)` (i.e., `Js.to_string(Js.Optdef(evt##.key))`) gives string as `Ã¥`

2021-09-14 02:27 UTC, cyrus- commented
@zhixiangteoh OK, it's fine if it doesn't work for now -- we can fold that issue into future Unicode support for Hazel more broadly.

There are some conflicts with the dev branch -- can you resolve those, then mark as ready for review?

2021-09-14 03:16 UTC, cyrus- commented
@zhixiangteoh is it ready for review now? If so, hit the "Ready for review" button

2021-09-27 21:54 UTC, cyrus- requested changes
looking close! in addition to the comments here, needs to be brought up to date with dev.

2021-09-27 21:54 UTC, cyrus- commented on src/hazelcore/Action_Exp.re
> +  //  #| comment 2
only seeing this behavior for blocks in synthetic position -- still has the previous behavior in analytic position

2021-09-27 21:54 UTC, cyrus- commented on src/hazelweb/ModelAction.re
> +  | SerializeZexpToConsole;
instead of a new action, add ZExp as another serialize_object case

2021-09-27 21:54 UTC, cyrus- commented on src/hazelweb/model/Program.re
> +  // switch (edit_state) {
don't include big chunks of commented out code in PRs

2021-11-03 04:27 UTC, cyrus- commented
@zhixiangteoh any updates here?

2021-11-03 04:51 UTC, zhixiangteoh commented
> @zhixiangteoh any updates here?

Aim to merge dev and push by end of week.

2021-11-03 18:29 UTC, cyrus- approved these changes

2021-11-03 18:30 UTC, merged