Parsing
hazelgrove/hazel pull request #558
Opened 2021-11-04 20:15 UTC by nj-wilson

Adds ability to import text into hazel as a program, as well as exporting the current program to plain text.

Currently is part of the hamburger menu as separate options (could easily be combined).
Import errors are shown, but currently are quite rudimentary, only showing what character caused a problem.

A couple commits are still local, for cleanup and additional tests.
There is a behavior difference with regard to empty or comment lines, but nothing that impacts correct programs.

ExternalLineBreak was added to Layout.t, but may be better as an Annot (for a future PR).
The module naming for the parser and lexer are somewhat confusing, i.e. Parsing.Parser, and Lexing.Lexer. Could use better names.

2021-11-05 17:10 UTC, cyrus- requested changes

2021-11-05 17:10 UTC, cyrus- commented on src/hazelcore/parse/dune
> +(include_subdirs no)
Since it can be its own library, lets move the parser out to the `src` directory instead of it being inside `hazelcore`. You can call it `hazeltext`.

2021-11-05 17:10 UTC, cyrus- commented on src/hazelcore/parse/print.re
> +};
let's add an end-to-end `print_exp : UHExp.t -> string` as well

2021-11-05 17:10 UTC, cyrus- commented on src/hazelcore/parse/test/test.ml
> +    | None -> Pretty.Layout.Text("")
this should be a failure case, not ""

2021-11-05 17:10 UTC, cyrus- commented on src/hazelcore/parse/parse.mly
> +  pat COLONCOLON pat { mk_binop $1 Operators_Pat.Cons $3 }
type annotations can now appear on any pattern, not just at the top level of a let or lambda

2021-11-05 17:10 UTC, cyrus- commented on src/hazelcore/parse/test/test.ml
> +  in map"
let's add a few tests of longer opseqs involving all of the various operators

2021-11-05 17:10 UTC, cyrus- commented on src/pretty/Layout.re
> +  | ExternalLinebreak
Let's use Annot in this PR rather than changing pretty

2022-05-13 17:06 UTC, cyrus- requested changes
Given that the popup text editor looks almost exactly like the structure editor UI, what if we actually had it integrated into the main editor as an editing mode toggle -- you can either edit using the structure editor or text editor, and there was a toggle to go back and forth which would trigger parsing/pretty printing as necessary?

In text mode, we could have it attempt to parse on every edit and run the evaluator as usual, but if parsing fails then you get the parse error instead of the result?

2022-05-13 20:03 UTC, nj-wilson commented
> 

Is an interesting idea, I shall look into it.
My only questions would be on how to display errors resulting in trying to go back to structured, though maybe that'll be taking care of from running the evaluator during edit. Though I do wonder if that would be problematic to run on every character typed.

I'll also have to see how easy it would be to switch the main text box between modes, or do some other method.

2022-05-19 03:48 UTC, cyrus- commented
You can use the same area in the UI that results are displayed to show errors, since no result is available when parsing fails, and the button to toggle back to structure editing can be disabled when there is a parse error. Don't worry about the performance cost of running the parser on each edit. If that becomes an issue down the line we can look into incremental parsing approaches, but nothing at the scale we're using Hazel should cause an issue. Learn OCaml already parses and pretty prints on every character. 

Shouldn't be too difficult GUI wise with the model-view-controller approach. When in text mode, render the text box you already have set up from the pop up in your branch, otherwise render the existing structure editor box.

2022-08-19 00:27 UTC, cyrus- commented
no longer relevant with the two other PRs.

2022-08-19 00:27 UTC, closed without merging