Hazeltext - Backend
hazelgrove/hazel pull request #598
Opened 2022-06-16 04:15 UTC by nj-wilson

Adds Hazeltext for parsing strings into hazel ASTs.
Reworks a few internals to accommodate this, mainly splitting
out memoization, and moving hazelweb/layout to hazelcore/layout.

Rewrites Examples to be strings ran through the parser.

2022-06-18 05:32 UTC, cyrus- requested changes

2022-06-18 05:32 UTC, cyrus- commented on src/hazelcore/layout/UHAnnot.re
> +  | ExternalLineBreak
ExpLineBreak instead of ExternalLineBreak?

2022-06-18 05:32 UTC, cyrus- commented on src/hazeltext/lex.mll
> +let newline = ['\n']
windows newlines?

2022-06-21 04:37 UTC, cyrus- approved these changes
Looks great, thanks!

2022-06-22 08:26 UTC, dedbox commented
Looks good!

Moving all those files into hazelcore in months-long feature branches is going to suck, but adding type aliases was nearly painless. The grammar is nice and clean.

2022-06-22 08:30 UTC, dedbox approved these changes
Looks good!

Moving all those files into hazelcore in months-long feature branches is going to suck, but adding type aliases was nearly painless. The grammar is nice and clean.

2022-06-22 16:25 UTC, merged