Built-in ADTs
hazelgrove/hazel pull request #863
Opened 2022-09-25 18:14 UTC by disconcision

This adds hardcoded algebraic data types. Types can be added in BuiltinADTs.re. Type names AND constructor names must be globally unique. This is enforced by startup assertions. Types may be (mutually) recursive.

This introduces basic type variables, intended to be supplanted by type aliases. These are of the form Var(string). These are globally scoped, and type equality is nominative, not structural, although this doesn't currently matter because of the enforced uniqueness constraints.

Constructors (Tags) are essentially a new kind of atomic literal. Constructors may be nullary, in which case their type is simply Var("name"), or unary, in which case their type is Arrow(something, Var("name")), where 'something' may be a tuple, to achieve n-ary constructors.

Given the above type assignment, constructors/tags are treated basically the same was as function literals by the static semantics. Both function and constructor application pass through the same Ap form. Constructors are first-class and may be used any way functions can. The dynamic semantics are essentially the same as for tuples.

This implementation is fully functional AFAICT. I've written a basic LC interpreter, which doesn't quite work due to casting issues, but these should (probably, hopefully) be resolved separately in the forthcoming casting branch

2022-09-28 02:59 UTC, cyrus- requested changes
Looks reasonable and straightforward, see a few comments but should be suitable to merge soon.

2022-09-28 02:59 UTC, cyrus- commented on src/haz3lcore/dynamics/Evaluator.re
> +  //| (Tag(_), Cast(d, ty, Unknown(_))) => matches(dp, d)
commented out code looks correct -- can strip off casts on tags

2022-09-28 02:59 UTC, cyrus- commented on src/haz3lcore/dynamics/Evaluator.re
> +  | (Ap(dp1, dp2), Ap(d1, d2)) =>
we probably want to special case Ap with a Tag immediately in the dp1 position as distinct from one with a var or other pattern there, which is typically not allowed (matching on arbitrary tags)

2022-09-28 02:59 UTC, cyrus- commented on src/haz3lcore/dynamics/Evaluator.re
> +          BoxedValue(Ap(d1, d2)) |> return
should be Indet if d2 is Indet

2022-09-28 02:59 UTC, cyrus- commented on src/haz3lcore/lang/Form.re
> +  ("ctr", (is_constructor, [mk_op(Exp, []), mk_op(Pat, [])])),
is a constructor different from a tag?

2022-09-28 02:59 UTC, cyrus- commented on src/haz3lcore/statics/BuiltinADTs.re
> +    "color",
let's use capitalized names for all types (not just the primitives)

2022-09-28 02:59 UTC, cyrus- commented on src/haz3lcore/statics/Statics.re
> +let typ_ann_after_fix = (self: Typ.self): Typ.t =>
this is kind of a hack? probably want to add UnboundVar to UTyp and have it behave like Unknown semantically (but errors still report the identifier inside)

2022-09-28 02:59 UTC, cyrus- commented on src/haz3lcore/statics/Typ.re
> +  //TODO: structural comparison?
not sure what structural comparison would mean here for built in ADTs

2022-09-29 17:42 UTC, disconcision commented
Leaving the issue of permissible tag positions aside until we do exhaustiveness. I agree that we'll likely want to restrict these in the future, to prohibit weird looking things if nothing else; on reflection it's not obvious to me that leaving it as-is actually complicates exhaustiveness checking; the general implementation i'm imagining would i think be ecumenical here

2022-09-29 17:42 UTC, merged