Haz3l improved casts
hazelgrove/hazel pull request #868
Opened 2022-09-29 03:15 UTC by disconcision

still buggy...

2022-09-29 03:30 UTC, disconcision commented
@cyrus still a bug here... do you see what's being miscast?
<img width="1325" alt="Screen Shot 2022-09-28 at 11 30 10 PM" src="https://user-images.githubusercontent.com/22436459/192932246-4bfc2dbd-d79c-4476-801b-07dd5930f624.png">

2022-09-29 03:32 UTC, disconcision commented
Also we probably need some more tests for this... any other ideas for what to try?

2022-09-29 04:57 UTC, cyrus- commented
On the last line of the elaboration, missing a cast to ? on the "x + 1"
operation, and each element of the list literal should also have a cast to
? because they are all in analytic position against ?. The function
argument as a whole should also be cast to ?.

The function body seems right if I'm reading those casts correctly...

On Wed, Sep 28, 2022 at 11:32 PM andrew blinn ***@***.***>
wrote:

> Also we probably need some more tests for this... any other ideas for what
> to try?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hazelgrove/hazel/pull/868#issuecomment-1261703681>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACEQPV6ZECDA4RSQ3C7YV3WAUEV5ANCNFSM6AAAAAAQYLADC4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-09-29 04:58 UTC, cyrus- commented
Also the type in the fixpoint annotation seems wrong, but the casts seem to
correctly cast to ?.

On Thu, Sep 29, 2022 at 12:56 AM Cyrus Omar ***@***.***> wrote:

> On the last line of the elaboration, missing a cast to ? on the "x + 1"
> operation, and each element of the list literal should also have a cast to
> ? because they are all in analytic position against ?. The function
> argument as a whole should also be cast to ?.
>
> The function body seems right if I'm reading those casts correctly...
>
> On Wed, Sep 28, 2022 at 11:32 PM andrew blinn ***@***.***>
> wrote:
>
>> Also we probably need some more tests for this... any other ideas for
>> what to try?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/hazelgrove/hazel/pull/868#issuecomment-1261703681>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AACEQPV6ZECDA4RSQ3C7YV3WAUEV5ANCNFSM6AAAAAAQYLADC4>
>> .
>> You are receiving this because you are subscribed to this thread.Message
>> ID: ***@***.***>
>>
>

2022-10-04 17:34 UTC, disconcision commented
just adding a list of minified erroring examples to check against later:
<img width="739" alt="Screen Shot 2022-10-04 at 1 33 58 PM" src="https://user-images.githubusercontent.com/22436459/193887649-a1d4057b-25d8-4f2d-97b4-fb0e10ba8117.png">
<img width="739" alt="Screen Shot 2022-10-04 at 1 33 52 PM" src="https://user-images.githubusercontent.com/22436459/193887652-033b83c8-46e3-4bba-ac84-274c070735a2.png">
<img width="739" alt="Screen Shot 2022-10-04 at 1 33 48 PM" src="https://user-images.githubusercontent.com/22436459/193887653-9a617d9c-907b-4a04-90db-d5f1727c6f04.png">
<img width="739" alt="Screen Shot 2022-10-04 at 1 33 37 PM" src="https://user-images.githubusercontent.com/22436459/193887654-39a7335d-e5bc-4ffc-8218-c65ade8d51ec.png">
<img width="739" alt="Screen Shot 2022-10-04 at 1 33 27 PM" src="https://user-images.githubusercontent.com/22436459/193887656-ecd0c3b5-7024-48fb-922c-a854b5dcbe22.png">

2022-10-12 21:50 UTC, disconcision commented
still some problematic cases:
<img width="904" alt="Screen Shot 2022-10-12 at 5 50 11 PM" src="https://user-images.githubusercontent.com/22436459/195454696-f39ca145-c7e9-4041-9149-3f5fd39e1cb1.png">
<img width="904" alt="Screen Shot 2022-10-12 at 5 50 04 PM" src="https://user-images.githubusercontent.com/22436459/195454697-74a3eb35-f8f2-4b2e-94d2-df5ab4322df9.png">
<img width="606" alt="Screen Shot 2022-10-12 at 5 49 27 PM" src="https://user-images.githubusercontent.com/22436459/195454698-43040f35-c27b-4a02-bbb8-231fe4102972.png">

2022-10-12 21:51 UTC, disconcision commented
@cyrus still some weird stuff going on here, see above

2022-10-12 21:53 UTC, cyrus- commented
First case seems to not be doing synpatternvar correctly anymore -- shouldn't need a cast there since x and y are both synthetic.

2022-10-12 21:54 UTC, cyrus- commented
third case... how did there end up being a cast from a list type on the function? that's very odd. can you show the unevaluated elaboration?

2022-10-12 21:56 UTC, cyrus- commented
second case seems to be missing casts to ? on the arguments of the function ap at the bottom (and maybe some others in the function, but at least that)

2022-10-26 21:18 UTC, disconcision commented
@cyrus- minified version of the remaining casting bug:
<img width="1149" alt="Screen Shot 2022-10-26 at 5 16 37 PM" src="https://user-images.githubusercontent.com/22436459/198140076-c01491a0-86f5-4d78-bebc-2497eb424492.png">

the problem's immediate cause seems to be the highlighted case we added here:
<img width="773" alt="Screen Shot 2022-10-26 at 5 16 49 PM" src="https://user-images.githubusercontent.com/22436459/198140094-0dd73e67-fb35-469d-a0de-8ef24123fe8b.png">

2022-10-27 01:21 UTC, tonyfettes commented
I just discovered that I can bypass the type-checking of if expression with a handcrafted fix point
![image](https://user-images.githubusercontent.com/29998228/198166580-c5f70951-426d-42c2-9220-251ba31520db.png)
I'm not sure if this is the ideal behaviour, and I'm also not totally clear what goes wrong here, but after some digging, I suspect putting cast after almost everything (in this example) is not a wise decision? See
https://github.com/hazelgrove/hazel/blob/haz3l-improved-casts/src/haz3lcore/dynamics/elaborator.re#L83

The dump of problematic casts.
![image](https://user-images.githubusercontent.com/29998228/198168455-3aef2576-0a32-4875-bfa0-b7e2299e7b40.png)

2022-10-27 07:08 UTC, cyrus- commented
> @cyrus- minified version of the remaining casting bug: <img alt="Screen Shot 2022-10-26 at 5 16 37 PM" width="1149" src="https://user-images.githubusercontent.com/22436459/198140076-c01491a0-86f5-4d78-bebc-2497eb424492.png">
> 
> the problem's immediate cause seems to be the highlighted case we added here: <img alt="Screen Shot 2022-10-26 at 5 16 49 PM" width="773" src="https://user-images.githubusercontent.com/22436459/198140094-0dd73e67-fb35-469d-a0de-8ef24123fe8b.png">

I'm not sure why the function inside the fixpoint shows a cast to `? -> ?` since it is already of that type? That might be causing some issues with the ap?

2022-10-27 07:17 UTC, cyrus- commented
I don't see how that issue would cause the exception you're seeing though. 

The result of `g 2` should be `[]<[?] => ?>` but then that should be cast to `[?]` as indicated there, which should be a successful cast leaving just `[]`... might need to investigate which of those steps isn't happening correctly.

2022-10-27 07:22 UTC, cyrus- commented
> I just discovered that I can bypass the type-checking of if expression with a handcrafted fix point ![image](https://user-images.githubusercontent.com/29998228/198166580-c5f70951-426d-42c2-9220-251ba31520db.png) I'm not sure if this is the ideal behaviour, and I'm also not totally clear what goes wrong here, but after some digging, I suspect putting cast after almost everything (in this example) is not a wise decision? See https://github.com/hazelgrove/hazel/blob/haz3l-improved-casts/src/haz3lcore/dynamics/elaborator.re#L83
> 
> The dump of problematic casts. ![image](https://user-images.githubusercontent.com/29998228/198168455-3aef2576-0a32-4875-bfa0-b7e2299e7b40.png)

@tonyfettes (you can make a separate issue for this kind of thing, not sure its related to this PR.)

2022-10-27 14:09 UTC, tonyfettes commented
> > I just discovered that I can bypass the type-checking of if expression with a handcrafted fix point ![image](https://user-images.githubusercontent.com/29998228/198166580-c5f70951-426d-42c2-9220-251ba31520db.png) I'm not sure if this is the ideal behaviour, and I'm also not totally clear what goes wrong here, but after some digging, I suspect putting cast after almost everything (in this example) is not a wise decision? See https://github.com/hazelgrove/hazel/blob/haz3l-improved-casts/src/haz3lcore/dynamics/elaborator.re#L83
> > The dump of problematic casts. ![image](https://user-images.githubusercontent.com/29998228/198168455-3aef2576-0a32-4875-bfa0-b7e2299e7b40.png)
> 
> @tonyfettes (you can make a separate issue for this kind of thing, not sure its related to this PR.)

This behaviour only shows in this PR, not in haz3l-tests, so I thought it's better to post here. I could also open an issue, but I'm a bit worried about confusing others who don't keep track of this PR.

2022-10-27 14:11 UTC, cyrus- commented
Ah ok if it's only on this pr then that's fine, sorry about that. @disconcision can you take a look

2022-10-27 15:12 UTC, disconcision commented
> I'm not sure why the function inside the fixpoint shows a cast to ? -> ? since it is already of that type?

@cyrus- : isn't the function of type ? -> [?]

2022-10-27 15:19 UTC, cyrus- commented
> > I'm not sure why the function inside the fixpoint shows a cast to ? -> ? since it is already of that type?
> 
> @cyrus- : isn't the function of type ? -> [?]

It's in analytic position, and the elaboration itself shows a cast on `[]` to `?`.

2022-10-27 15:42 UTC, disconcision commented
@tonyfettes, @cyrus- : statics isn't affected by casting, so that's orthogonal. the difference is likely with the new mode for function position (previously function position was analytic against ?->?). looks like currently that function body is ending up in analytic against ?, hence no error holes being drawn.

here's a minified version with the same essential statics:
<img width="438" alt="2022-10-27 11_41_16-hazel" src="https://user-images.githubusercontent.com/22436459/198335803-af56da57-c139-4938-8340-ffb7f46f13c1.png">

which i believe is functioning as-expected? the argument is analyzed against ?, producing the observed behavior

2022-10-27 15:45 UTC, disconcision commented
> It's in analytic position, and the elaboration itself shows a cast on [] to ?.

but the types which cast insertion is based on are the types from the statics, not the types after casting

2022-10-27 16:25 UTC, tonyfettes commented
@disconcision That makes sense, and thank you for the explanation.

2022-10-27 20:04 UTC, cyrus- commented
> > It's in analytic position, and the elaboration itself shows a cast on [] to ?.
> 
> but the types which cast insertion is based on are the types from the statics, not the types after casting

Yes, but its in analytic position. I think the commented out `Fun(_), _` case is maybe the culprit here -- we do want that case because Fun already knows how to propagate the expected type into the body by matching?

2022-10-28 17:02 UTC, cyrus- commented
Did that fix it?

2022-10-28 17:07 UTC, disconcision commented
<img width="1207" alt="Screen Shot 2022-10-28 at 1 02 55 PM" src="https://user-images.githubusercontent.com/22436459/198692684-e72bd5de-2b5a-4415-ba6d-f97aaad9d4bc.png">
@cyrus adding back the fun case prevents the previous suggestion. still a bit foggy on the justification. There are still problematic listlit cases though, such as above. here the actual type of xs is ?, due to the annotation, and the expected type is [?], so it gets a [?]=>? cast, triggering the InvalidBoxedListLit exception. or is this an issue with the cons casting/statics?

2022-10-28 17:17 UTC, cyrus- commented
I think the issue there is that the case shouldn't have a cast on it, since its in analytic position. I think we need that special case in the `wrap` function for anything that has a special analytic case?

2022-10-28 19:02 UTC, disconcision commented
okay, no casts on case. i think that exhausts our special analytic cases? 
still getting this guy (invalid boxed bool lit from being cast to unknown typehole)
<img width="678" alt="Screen Shot 2022-10-28 at 3 00 46 PM" src="https://user-images.githubusercontent.com/22436459/198712551-157d27de-7e21-44ac-9fc8-0d0bfacdc597.png">

2022-10-28 21:10 UTC, cyrus- commented
The list lit `[true]` shouldn't need a cast to `[?]` on it since the `true`
is cast to `?` -- I guess thats another analytic special case since the
element types propagate down.

On Fri, Oct 28, 2022 at 3:02 PM andrew blinn ***@***.***>
wrote:

> okay, no casts on case. i think that exhausts our special analytic cases?
> still getting this guy (invalid boxed bool lit from being cast to unknown
> typehole)
> [image: Screen Shot 2022-10-28 at 3 00 46 PM]
> <https://user-images.githubusercontent.com/22436459/198712551-157d27de-7e21-44ac-9fc8-0d0bfacdc597.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hazelgrove/hazel/pull/868#issuecomment-1295351462>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACEQPRHO737XFHCSTLZRYDWFQPLHANCNFSM6AAAAAAQYLADC4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-31 18:21 UTC, disconcision commented
@cyrus this is ready for another look. I'm currently not aware of any more examples that throw exceptions. We need to comment the wrap function better, explain which cases are cast. I refactored and clarified the wrap logic somewhat, but the only substantive change is to the listlit case, pursuant to the above

2022-11-09 00:15 UTC, disconcision commented
made the changes we talked about... couple things... first, the new tuple rule is causing errors again:

<img width="1248" alt="Screen Shot 2022-11-08 at 7 13 50 PM" src="https://user-images.githubusercontent.com/22436459/200704570-fd33b78f-8017-408f-b2f4-3915255be093.png">
<img width="1248" alt="Screen Shot 2022-11-08 at 7 13 34 PM" src="https://user-images.githubusercontent.com/22436459/200704574-65327fe7-d9a9-4bf8-8c2a-f717c831e4b1.png">

second, you mentioned fix as a form that needs a special rule... but what should it be?

2022-11-23 19:11 UTC, cyrus- commented
@disconcision There is a small merge conflict that needs to be resolved now in the Let case of the elaborator due to the recently merged PR adding function name metadata

2022-11-23 19:33 UTC, cyrus- requested changes
just a few more cleanup / minor issues

2022-11-23 19:33 UTC, cyrus- commented on src/haz3lcore/dynamics/DH.re
>      | (ListLit(_, _, _, _, []), List(_)) =>
this may no longer be necessary?

2022-11-23 19:33 UTC, cyrus- commented on src/haz3lcore/dynamics/Evaluator.re
> +type blah = list(list((Typ.t, Typ.t)));
pretty blah name for a type. is it used somewhere?

2022-11-23 19:33 UTC, cyrus- commented on src/haz3lcore/dynamics/elaborator.re
> +      /* Things in function position get cast to an arrow type */
nit: get cast to the matched arrow type. maybe make the `_` case an Arrow case and assert in the fall through case that it should never happen in this and the cases below

2022-11-23 19:33 UTC, cyrus- commented on src/haz3lcore/dynamics/elaborator.re
> +      /*| Tuple(_) =>
can delete

2022-11-23 19:33 UTC, cyrus- commented on src/haz3lcore/dynamics/elaborator.re
> +      | FixF(_) =>
I don't think this case ever arises but in principle, it should behave like Let in that the expected type is passed down in the statics so I'd put it down in the next group of cases

2022-11-23 19:33 UTC, cyrus- commented on src/haz3lcore/statics/Statics.re
> +    /*| (Ana(Unknown(SynSwitch)), Joined(tys_syn))*/
can be removed

2022-11-23 19:33 UTC, cyrus- commented on src/haz3lweb/view/dhcode/layout/DHDoc_Exp.re
> +        //TODO(andrew): reinstate
not sure what this means

2022-11-23 19:33 UTC, cyrus- commented on src/haz3lweb/view/dhcode/layout/DHDoc_Exp.re
> +        //TODO(andrew): reinstate
is this still a problem?

2023-01-20 03:04 UTC, cyrus- approved these changes

2023-01-20 03:12 UTC, merged