Haz3l mixed ctx
hazelgrove/hazel pull request #894
Opened 2022-10-04 14:47 UTC by AlienKevin

Added mixed Ctx for storing both term and type variables in context.

2022-10-10 18:10 UTC, cyrus- commented
Entries in the context are doubled up: 
![Screen Shot 2022-10-10 at 2 08 07 PM](https://user-images.githubusercontent.com/280638/194928019-39d1a794-33ca-4619-a908-cd23cbe88466.png)

2022-10-13 01:19 UTC, LighghtEeloo commented
This happens because we are preserving all bindings in our context. We've just fixed it by adding a `filter_duplicate` function and call it before showing it in our context inspector (d09c683).

2022-10-13 15:02 UTC, LighghtEeloo commented
The latest commit (786b219) fixes the duplicate bindings in a recursive let definition.

2022-10-20 14:50 UTC, LighghtEeloo commented on src/haz3lcore/statics/Kind.re
> +  | Singleton;
Change to Typ

2022-10-20 14:51 UTC, LighghtEeloo commented on src/haz3lcore/statics/Ctx.re
>  type entry = {
Use LIst.t(entry)

2022-10-20 14:56 UTC, cyrus- requested changes

2022-10-20 14:56 UTC, cyrus- commented on src/haz3lcore/statics/Ctx.re
> +let lookup_typ = (ctx: t, x) =>
rename to lookup_var (and lookup_tvar)

2022-10-20 14:56 UTC, cyrus- commented on src/haz3lcore/statics/Ctx.re
> +  value,
create separate Var and TVar types and have the context be a list of entries, which can be either Var or TVar entries

2022-10-20 14:56 UTC, cyrus- commented on src/haz3lcore/statics/Kind.re
> +  | Singleton;
rename to Type

2022-10-20 14:56 UTC, cyrus- commented on src/haz3lweb/view/CtxInspector.re
> +      text(name),
have it say "type A" for type entries

2022-10-27 00:17 UTC, AlienKevin commented
@cyrus- All requested changes are made. We tested the mixed ctx in the Hazel editor and the context looks fine. We think it's ready to merge.

2022-10-27 14:43 UTC, cyrus- requested changes
should be ready to go after the small change suggested

2022-10-27 14:43 UTC, cyrus- commented on src/haz3lcore/statics/Statics.re
> +      ~ctx=[VarEntry({name, id: Term.UPat.rep_id(upat), typ}), ...ctx],
define a Ctx.extend function instead of relying on the implementation type

2022-10-27 14:55 UTC, cyrus- approved these changes

2022-10-27 14:55 UTC, merged