Add pipeline operator
hazelgrove/hazel pull request #924
Opened 2022-10-26 18:58 UTC by alan123piano

This pull request is only three lines. It adds a pipeline operator. Some things to note:

* Since the current parsing engine doesn't support invalid partial states for operators, I add an auxillary operator '|' which creates a binary op form. Perhaps this can be fixed if the parsing engine is reworked, or if bitwise-or is added.
* The mold for 'Rule' has some ambiguous states with the pipeline operator '|>'. Of particular concern is that if you add a whitespace after an expression like '1 | ', then it instantly becomes a Rule as per the deferred expansion rule (without a chance to change it into a pipeline operator).
* The evaluation for the pipeline operator is the same as function application, since this operator is just sugar.

![image](https://user-images.githubusercontent.com/58316591/198112574-838ea5cd-6214-4481-b9f4-4a3fe27fb715.png)

2022-10-27 17:35 UTC, cyrus- requested changes
Looks good but lets update the LangDocs description to describe what |> does specifically.

2022-11-04 19:50 UTC, cyrus- commented
@alan123piano marking as draft -- can you look into the langdocs thing soon and then mark as ready for review when its good to go. feel free to reach out to @hannahpotter about the langdocs modules if you need a pointer.

2023-01-05 21:10 UTC, alan123piano commented
This works WITH the haz3l-improved-casts branch - don't merge this yet unless you approve that branch as well. I've put up some LangDocs messages as well.

2023-11-10 05:48 UTC, cyrus- approved these changes

2023-11-10 05:48 UTC, merged