Add undefined keyword
hazelgrove/hazel pull request #926
Opened 2022-11-02 03:08 UTC by shbhgrwl

Adds an undefined keyword to the language. The goal is to provide users the ability to express intent not to fill an empty hole. This may be useful when there is no coherent value to return in certain branches. For example, consider the the following operation on lists:
```
let head = fun xs -> case xs
    | hd::tl => hd
    | nil => undefined
end in
(head([2, 3, 4]), head(nil))
```
This evaluates to `(2, undefined)` because the left has a coherent value, but the head of an empty list is undefined.

The one difference between an empty hole and `undefined` is that `undefined` should not be a valid pattern in a case expression. I'm still working on making that behavior work properly.

This could be extended by allowing users to specify an error message along with the undefined value to be more clear as to what error led to the undefined behavior. This would require a more major overhaul which adds the possibility for a message/value associated with any empty hole (which could be a desirable feature in itself)

2022-11-04 19:49 UTC, cyrus- commented
@shbhgrwl marking as draft -- click ready for review when it's up to date with haz3l-tests and ready to look at!

2022-11-16 00:30 UTC, shbhgrwl commented
Documentation started working properly on my machine after clearing out the browser cache, but prior to clearing out the cache I was receiving an `async_js` error -- I wonder if that has something to do with the failing build

2022-11-16 18:10 UTC, cyrus- commented
@shbhgrwl Hm, can you reproduce the issue again from a clean cache?

2022-11-17 04:48 UTC, shbhgrwl commented
once I cleaned my cache I no longer get the error on my machine (including after using/reloading the webpage such that the cache isn't clean). @hannahpotter seemed to think it was some sort of bug with serialization of new language documentation

2022-11-21 03:54 UTC, cyrus- requested changes, later dismissed

2022-11-21 03:54 UTC, cyrus- commented on src/haz3lcore/dynamics/elaborator.re
> +    | Undefined => Some(DHExp.EmptyHole(u, 0))
Let's add an undefined to DHExp as well so results are a bit more comprehensible.

2022-11-21 03:54 UTC, cyrus- commented on src/haz3lweb/LangDocMessages.re
> +    message: "Undefined expression. The undefined expression denotes the lack of a value. It is similar to an empty hole, but with no intent to define it in the future.",
"denotes the lack of a value" -> "can be used to define a partial function"

2022-12-05 04:56 UTC, shbhgrwl commented
I've added `undefined` to `DHExp`, so it now evaluates to `undefined` rather than an empty hole. additional operations are indeterminate, so, for example, `undefined + 3` will show a result of `undefined + 3`

2022-12-05 22:10 UTC, cyrus- commented
Great. If it is ready for review, you can click the Ready for review button. Make sure it is up-to-date with haz3l-tests.

2023-01-21 15:58 UTC, cyrus- commented
@shbhgrwl can you resolve the small merge conflict and then mark as ready for review again

2023-11-10 05:50 UTC, cyrus- commented
As discussed in office hours, undefined should not evaluate to what looks like a string literal. It should be its own DHExp form.

<img width="779" alt="image" src="https://github.com/hazelgrove/hazel/assets/280638/5ab64c38-64fb-418b-bc7d-b888ee3d019e">

2023-11-12 20:08 UTC, linsyking commented
> As discussed in office hours, undefined should not evaluate to what looks like a string literal. It should be its own DHExp form.
> 
> <img alt="image" width="779" src="https://user-images.githubusercontent.com/280638/281970056-5ab64c38-64fb-418b-bc7d-b888ee3d019e.png">

This should be fixed now

2023-12-11 18:51 UTC, cyrus- commented
@linsyking can you fix the merge conflicts here

2023-12-11 20:06 UTC, linsyking commented
Still need to update the `Transition` module

2023-12-18 16:28 UTC, linsyking commented
> @linsyking can you fix the merge conflicts here

It should work now, but it seems that the latest hazel cannot run in chrome (chrome ver: 120.0.6099.109).

2024-02-29 05:35 UTC, cyrus- commented
@linsyking do you have time to take another look at the latest merge conflicts and getting this over the line?

2024-07-25 16:47 UTC, cyrus- commented
Closing in favor of #1315

2024-07-25 16:47 UTC, closed without merging