Refactor ExplainThis code to be more easily extensible
hazelgrove/hazel pull request #993
Opened 2023-02-18 02:20 UTC by hannahpotter

2023-03-17 18:07 UTC, disconcision requested changes
Solid progress in general. Some stylistic quibbles in the comments, I feel like we can still abstract and condense things a bit. A few points of uncertainty around some of the types.

There's a remaining larger-scale structure issue which is at least worth thinking about addressing. Right now, the entire langdocs is getting put in the model. Really though it's conceptually two pieces: The messages, which are statically invariant, and the UI state (three globals (show docs, show highlights, specificity), and three more specific options for groups, forms, and examples respectively).

The model should ideally only contain state, both conceptually and practically (we'll likely end up de/serializing a bunch of redundant content). Not a huge deal at the moment but it's the kind of baggage I'm wary about accumulating.

I'm guessing it ended up this way because otherwise it would seem like we have to duplicate the entire data hierarchy of groups and examples, but I think we can probably avoid this with clever types.. wondering if you've thought about this; if this isn't clear we could try to work up a spec together, i think it could potentially end up simplifying other things, but there's some design complexity as well. i think it's at least worth chatting about this option but it's not an outright blocker from my perspective.

To facilitate this it would be helpful I think to have a (quick, basic) conceptual diagram (either drawn or just prose) which describes the architecture of the system at a high level, i.e. describes the relation between groups, explanation/forms, and examples, and their associated kinds of UI state.

2023-03-17 18:07 UTC, disconcision commented on src/haz3lweb/explainthis/ExplainThisForm.re
> +  | BasicFun
minor but for this kind of type I feel it's nice to break it up into related chunks, ie
| Fun(fun_examples);

type fun_examples =
| Basic
| Wild
...

Not sure if strictly useful here but sometimes helps for dividing functions into more manageable, related chunks

2023-03-17 18:07 UTC, disconcision commented on src/haz3lweb/explainthis/ExplainThisMessages.re
> +type messages = {
not sure its strictly necessary to have "_group" in each name now that these are disambiguated by type. i would be tempted just to pluralize them instead; not a big deal tho

2023-03-17 18:07 UTC, disconcision commented on src/haz3lweb/explainthis/ExplainThisMessages.re
> +  | FunctionEmptyHole =>
all of these cases could be abstracted into a general fn, something similar to:
```
(group, base) => {
  let general = group.function_exp;
  let options = [
      (general.form.id, general.expansion_label),
      (base.form.id, base.expansion_label),
    ];
  (general.selected?general.form:base.form, options)
}
```

2023-03-17 18:07 UTC, disconcision commented on src/haz3lweb/explainthis/ExplainThisMessages.re
> +        print_endline(
debug print?

2023-03-17 18:07 UTC, disconcision commented on src/haz3lweb/explainthis/FunctionExp.re
> +let function_str_group = "function_str_group";
are we still using these strings for anything? thought they were being moved into the types

2023-03-17 18:07 UTC, disconcision commented on src/haz3lweb/view/ExplainThis.re
> +                    Node.div(
i feel when things start to get to the point where indentation is deep enough that we start seeing one token per line its worth breaking off some fns/lets along semantic boundaries. like here maybe specificity could be a top-level fn (might be too annoying if theres too many parameters tho), and internally maybe
```
let update_group_selection =
  _ => inject(Update.UpdateExplainThisMessages(
            ExplainThisMessages.UpdateGroupSelection(group_id, id))
         );
```
cuz then the handler just reads as `Attr.on_click(update_group_selection)` and its easy to see at a glance what it does (perhaps name could be better, just guessing what the most pertinent aspect is)

2023-03-17 18:07 UTC, disconcision commented on src/haz3lweb/explainthis/ExampleUtil.re
> +open Haz3lcore;
I think just merge this file into Example... we might want to rename Example too, I dunno. I don't think it's used elsewhere atm, it was kind of a transitional construct; open to a more use-descriptive name. Does all of your syntax construction go through here? In any case, I think we should consolidate all manual syntax construction in one file, and Example is probably the place for now. The string Form names were also kind of a transitory thing and I didn't expect them to become load-bearing like this. But I think it's fine for now if we just consolidate all this kind of thing in Example, and then it can be update en-mass if I find a better way to handle manual syntax construction, as I hope to do for assistant stuff.

2023-03-17 18:07 UTC, disconcision commented on src/haz3lweb/explainthis/FunctionExp.re
> +type function_bool_group = {
i'm a bit confused by these types... they all seem to be isomorphic (all of their fields have the same types). usually in the case where record fields share common types you'd break those out to a top-level record. in this case - without me fully understanding the use - i'd expect to se something like:
```
type base =
| MultiHole
| Wild
| Float ...

type function_group = {
  base,
  id: group_id,
  exp: form_option,
  base_exp: form_option
};
```
I don't think this is quite right though, as I don't understand the use exactly. But this seems like it should be split into a variant part and a record part.

2023-03-17 18:07 UTC, disconcision commented on src/haz3lweb/explainthis/ExplainThisMessages.re
> +[@deriving (show({with_path: false}), sexp, yojson)]
update is pretty important, i think this is worth breaking out into a separate file. also, the explainthis folder has a lot of files... i think it's worth adding a subfolder called maybe 'data' for the files that are basically just the data for different kinds of messages, and having the top-level files be the logic + utilies

2023-06-10 02:44 UTC, cyrus- commented
@hannahpotter this has some conflicts with dev. what is the status of resolving the things @disconcision mentioned?

2023-08-03 05:19 UTC, hannahpotter commented on src/haz3lweb/explainthis/ExplainThisMessages.re
> +[@deriving (show({with_path: false}), sexp, yojson)]
Done. See ExplainThisUpdate and explainthis/data

2023-08-03 05:21 UTC, hannahpotter commented on src/haz3lweb/explainthis/ExampleUtil.re
> +open Haz3lcore;
Done. All moved to Example

2023-08-03 05:22 UTC, hannahpotter commented on src/haz3lweb/explainthis/ExplainThisMessages.re
> +        print_endline(
Yes. Removed

2023-08-03 05:24 UTC, hannahpotter commented on src/haz3lweb/explainthis/ExplainThisMessages.re
> +  | FunctionEmptyHole =>
Code changed in ExplainThisModel so this isn't relevant anymore

2023-08-03 22:57 UTC, hannahpotter commented on src/haz3lweb/explainthis/FunctionExp.re
> +type function_bool_group = {
Addressed. See ExplainThisForm.

2023-08-03 23:05 UTC, hannahpotter commented on src/haz3lweb/view/ExplainThis.re
> +                    Node.div(
Updated.

2023-08-03 23:08 UTC, hannahpotter commented on src/haz3lweb/explainthis/FunctionExp.re
> +let function_str_group = "function_str_group";
Correct. They aren't being used anymore. They should all be removed now.

2023-08-03 23:09 UTC, hannahpotter commented on src/haz3lweb/explainthis/ExplainThisMessages.re
> +type messages = {
Group names changed.

2023-08-03 23:58 UTC, hannahpotter commented on src/haz3lweb/explainthis/ExplainThisForm.re
> +  | BasicFun
Broken up more,

2023-08-04 00:01 UTC, hannahpotter commented
Conflicts with dev fixed and comments addressed.

2023-08-04 00:02 UTC, hannahpotter commented
ExplainThisForm - defines the structure of the different messages, examples, groups, etc. This would be where people adding new messages would "register" them.
ExplainThisModel - defines the structure of the stateful parts of the messages, groups, etc. This is connected to ExplainThisForm by the IDs. People just adding new messages shouldn't have to touch this. I wrote in some checking code that should only be hit if someone either makes a mistake in defining a message in a way that won't be checked statically or if someone messes up the model.
ExplainThisMessages is no more
ExplainThisUpdate - handles all the updates to the model. People just adding new messages shouldn't have to touch this.
HoleExp - has some examples of how someone would define simple messages
FunctionExp - has some examples of how someone would define more complicated messages/groups
ExplainThis - all of the drawing code. People just adding new messages would just need to define the pattern that needs to be matched on and call the correct message (simple example ~line 587, more complicated example ~lines 604-650)

2023-08-04 00:14 UTC, hannahpotter commented on src/haz3lweb/LocalStorage.re
> -    try(LangDocMessages.deserialize(data)) {
This will mean that if a form is removed from ExplainThisForm that had saved data for it, the ExplanThisModel won't be loaded in.

2023-08-21 19:06 UTC, disconcision commented
going to do a review, but general question: could you provide a short step-by-step guide to the full process of adding docs for a new syntactic form? just want something to contextualize the new setup for an implementor pov

2024-01-19 06:34 UTC, disconcision approved these changes

2024-01-19 06:34 UTC, disconcision commented on src/haz3lweb/Example.re
> +
This Example file is only used for explainthis now; let's move it to the explainthis directory and maybe rename it

2024-01-19 06:34 UTC, disconcision commented on src/util/ListUtil.re
> +let rec split =
stick this with the other split fns below, or if possible just make it a wrapper for one of them

2024-01-19 06:34 UTC, disconcision commented on src/haz3lweb/explainthis/data/CaseExp.re
> +/*let case_exp_rules: form = {
rm or document

2024-01-19 06:34 UTC, disconcision commented on src/haz3lweb/explainthis/ExplainThisForm.re
> +type bin_op_sub_form_id =
this type seems like it's exactly isomorphic to the existing bin_op type in TermBase? is there a reason for having it separate?

2024-01-19 06:40 UTC, disconcision commented
@cyrus- this is ready to be merged ASAP. I made some changes, mostly cosmetic.

In re-adding the Pipeline operator docs, I streamlined the process a bit for adding new simple docs (simple == one-element groups). PipelineExp.re serves as an exemplar. Adding a new language forms should now be as simple as imitating that file and following the types. (Existing docs could be refactored along the same lines to make them much shorter)

2024-01-23 23:45 UTC, disconcision commented
This is (basically) all you need to specify to add a new form now:
<img width="938" alt="Screenshot 2024-01-23 at 6 43 48 PM" src="https://github.com/hazelgrove/hazel/assets/22436459/58300ee4-dbc1-472a-a2bc-f5dd65b83c26">

2024-01-23 23:59 UTC, merged