Hole context generation and unit tests
hazelgrove/hazel pull request #995
Opened 2023-02-24 19:38 UTC by ruiz-m

This adds an extension to the dhexp_of_uexp function to return the hole context generated by the given uexp.
It also adds unit tests for the dhexp_of_uexp function using the Tezt library.

2023-06-27 03:19 UTC, cyrus- requested changes
I'm getting an error when I run `make test` -- is that the right way to run the tests or am I missing something?

2023-06-27 03:19 UTC, cyrus- commented on Makefile
> +	dune exec src/haz3ltest/haz3ltest.exe -- --regression-dir src/haz3ltest/regressions
can you add a blurb to the README file for how to run tests (I removed it recently from dev since it was out of date)

2023-07-18 17:51 UTC, cyrus- commented
@ruiz-m can you take a look at the small changes above

2023-07-21 22:22 UTC, cyrus- requested changes

2023-07-21 22:22 UTC, cyrus- commented on README.md
> +You can run all of the unit tests located in `src/hazelcore/test` by running `make test`.
the tests are in `src/haz3ltest` not `src/hazelcore/test`

2023-07-21 22:22 UTC, cyrus- commented on README.md
> +Unit tests are written using the Tezt library.
Make the words "Tezt library" a link to the documentation for the library.

2023-07-21 22:22 UTC, cyrus- commented on src/haz3lcore/dynamics/Delta.rei
> +type t = MetaVarMap.t((hole_sort, Typ.t, Ctx.t));
should take `val_ty` as argument

2023-07-21 22:22 UTC, cyrus- commented on src/haz3lcore/dynamics/Delta.rei
> +type t = MetaVarMap.t((hole_sort, Typ.t, Ctx.t));
should take `val_ty` as argument

2023-07-24 18:29 UTC, ruiz-m commented
I have a few concerns. Since hole closure environment is not used in type assignment like in the paper, Ctx.t in val_ty is never actually used.

2023-07-25 20:19 UTC, cyrus- commented
Yeah I think it might be helpful to rebase this on adt-defs-after and resolve the conflicts there. Also, I was thinking that Delta.t might be derivable directly from the info map?

2023-08-01 18:53 UTC, cyrus- commented
Closing this PR in favor of separate PRs for test framework and hole context stuff

2023-08-01 18:53 UTC, closed without merging